% Mizar problem: t53_yellow_6,yellow_6,2667,57 
fof(t53_yellow_6, conjecture,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  (m4_yellow_6(B, A) =>  (k12_yellow_6(k13_yellow_6(A, B))=B <=> v8_yellow_6(B, A)) ) ) ) ) ).
fof(abstractness_v1_orders_2, axiom,  (! [A] :  (l1_orders_2(A) =>  (v1_orders_2(A) => A=g1_orders_2(u1_struct_0(A), u1_orders_2(A))) ) ) ).
fof(abstractness_v1_pre_topc, axiom,  (! [A] :  (l1_pre_topc(A) =>  (v1_pre_topc(A) => A=g1_pre_topc(u1_struct_0(A), u1_pre_topc(A))) ) ) ).
fof(abstractness_v6_waybel_0, axiom,  (! [A, B] :  ( (l1_struct_0(A) & l1_waybel_0(B, A))  =>  (v6_waybel_0(B, A) => B=g1_waybel_0(A, u1_struct_0(B), u1_orders_2(B), u1_waybel_0(A, B))) ) ) ).
fof(antisymmetry_r2_hidden, axiom,  (! [A, B] :  (r2_hidden(A, B) =>  ~ (r2_hidden(B, A)) ) ) ).
fof(d10_xboole_0, axiom,  (! [A] :  (! [B] :  (A=B <=>  (r1_tarski(A, B) & r1_tarski(B, A)) ) ) ) ).
fof(d10_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  (l1_waybel_0(B, A) =>  (v1_yellow_6(B, A) =>  (v2_struct_0(B) | k4_yellow_6(A, B)=k3_funct_1(u1_waybel_0(A, B))) ) ) ) ) ) ).
fof(d12_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  &  (v4_orders_2(C) &  (v7_waybel_0(C) & l1_waybel_0(C, A)) ) )  =>  (m2_yellow_6(C, A, B) <=>  (? [D] :  ( (v1_funct_1(D) &  (v1_funct_2(D, u1_struct_0(C), u1_struct_0(B)) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(C), u1_struct_0(B))))) )  &  (r2_funct_2(u1_struct_0(C), u1_struct_0(A), u1_waybel_0(A, C), k1_partfun1(u1_struct_0(C), u1_struct_0(B), u1_struct_0(B), u1_struct_0(A), D, u1_waybel_0(A, B))) &  (! [E] :  (m1_subset_1(E, u1_struct_0(B)) =>  (? [F] :  (m1_subset_1(F, u1_struct_0(C)) &  (! [G] :  (m1_subset_1(G, u1_struct_0(C)) =>  (r1_orders_2(C, F, G) => r1_orders_2(B, E, k2_yellow_6(u1_struct_0(C), B, D, G))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d14_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  (B=k6_yellow_6(A) <=>  (! [C] :  (r2_hidden(C, B) <=>  (? [D] :  ( ( ~ (v2_struct_0(D))  &  (v4_orders_2(D) &  (v6_waybel_0(D, A) &  (v7_waybel_0(D) & l1_waybel_0(D, A)) ) ) )  &  (D=C & r2_hidden(u1_struct_0(D), k1_yellow_6(u1_struct_0(A)))) ) ) ) ) ) ) ) ) ).
fof(d15_yellow_6, axiom,  (! [A] :  (! [B] :  (l1_struct_0(B) =>  (! [C] :  ( (v1_relat_1(C) &  (v4_relat_1(C, A) &  (v1_funct_1(C) & v1_partfun1(C, A)) ) )  =>  (m3_yellow_6(C, A, B) <=>  (! [D] :  (r2_hidden(D, k2_relat_1(C)) =>  ( ~ (v2_struct_0(D))  &  (v4_orders_2(D) &  (v7_waybel_0(D) & l1_waybel_0(D, B)) ) ) ) ) ) ) ) ) ) ) ).
fof(d16_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  =>  (! [C] :  (m3_yellow_6(C, u1_struct_0(B), A) =>  (! [D] :  ( ( ~ (v2_struct_0(D))  &  (v4_orders_2(D) &  (v6_waybel_0(D, A) &  (v7_waybel_0(D) & l1_waybel_0(D, A)) ) ) )  =>  (D=k8_yellow_6(A, B, C) <=>  (g1_orders_2(u1_struct_0(D), u1_orders_2(D))=k3_yellow_3(B, k5_yellow_1(u1_struct_0(B), C)) &  (! [E] :  (m1_subset_1(E, u1_struct_0(B)) =>  (! [F] :  ( (v1_relat_1(F) & v1_funct_1(F))  =>  ( (r2_hidden(E, u1_struct_0(B)) & r2_hidden(F, u1_struct_0(k5_yellow_1(u1_struct_0(B), C))))  => k1_binop_1(u1_waybel_0(A, D), E, F)=k1_funct_1(u1_waybel_0(A, k7_yellow_6(u1_struct_0(B), A, C, E)), k1_funct_1(F, E))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d18_pboole, axiom,  (! [A] :  (! [B] :  ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) & v1_partfun1(B, A)) ) )  =>  (! [C] :  ( (v1_relat_1(C) &  (v4_relat_1(C, A) &  (v1_funct_1(C) & v1_partfun1(C, A)) ) )  =>  (! [D] :  ( (v1_relat_1(D) &  (v4_relat_1(D, A) &  (v1_funct_1(D) & v1_partfun1(D, A)) ) )  =>  (m2_pboole(D, A, B, C) <=>  (! [E] :  (r2_hidden(E, A) =>  (v1_funct_1(k1_funct_1(D, E)) &  (v1_funct_2(k1_funct_1(D, E), k1_funct_1(B, E), k1_funct_1(C, E)) & m1_subset_1(k1_funct_1(D, E), k1_zfmisc_1(k2_zfmisc_1(k1_funct_1(B, E), k1_funct_1(C, E))))) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d19_relat_1, axiom,  (! [A] :  (! [B] :  (v1_relat_1(B) =>  (v5_relat_1(B, A) <=> r1_tarski(k2_relat_1(B), A)) ) ) ) ).
fof(d1_binop_1, axiom,  (! [A] :  ( (v1_relat_1(A) & v1_funct_1(A))  =>  (! [B] :  (! [C] : k1_binop_1(A, B, C)=k1_funct_1(A, k4_tarski(B, C))) ) ) ) ).
fof(d1_funct_2, axiom,  (! [A] :  (! [B] :  (! [C] :  (m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B))) =>  ( ( (B=k1_xboole_0 => A=k1_xboole_0)  =>  (v1_funct_2(C, A, B) <=> A=k1_relset_1(A, B, C)) )  &  (B=k1_xboole_0 =>  (A=k1_xboole_0 |  (v1_funct_2(C, A, B) <=> C=k1_xboole_0) ) ) ) ) ) ) ) ).
fof(d21_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  (m4_yellow_6(B, A) <=> r1_tarski(B, k2_zfmisc_1(k6_yellow_6(A), u1_struct_0(A)))) ) ) ) ).
fof(d22_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  (m4_yellow_6(B, A) =>  (B=k12_yellow_6(A) <=>  (! [C] :  ( ( ~ (v2_struct_0(C))  &  (v4_orders_2(C) &  (v7_waybel_0(C) & l1_waybel_0(C, A)) ) )  =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_hidden(k4_tarski(C, D), B) <=>  (r2_hidden(C, k6_yellow_6(A)) & r2_hidden(D, k10_yellow_6(A, C))) ) ) ) ) ) ) ) ) ) ) ).
fof(d23_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  (m4_yellow_6(B, A) =>  (v4_yellow_6(B, A) <=>  (! [C] :  ( ( ~ (v2_struct_0(C))  &  (v4_orders_2(C) &  (v7_waybel_0(C) &  (v1_yellow_6(C, A) & l1_waybel_0(C, A)) ) ) )  =>  (r2_hidden(C, k6_yellow_6(A)) => r2_hidden(k4_tarski(C, k4_yellow_6(A, C)), B)) ) ) ) ) ) ) ) ).
fof(d24_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  (m4_yellow_6(B, A) =>  (v5_yellow_6(B, A) <=>  (! [C] :  ( ( ~ (v2_struct_0(C))  &  (v4_orders_2(C) &  (v7_waybel_0(C) & l1_waybel_0(C, A)) ) )  =>  (! [D] :  (m2_yellow_6(D, A, C) =>  (r2_hidden(D, k6_yellow_6(A)) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  (r2_hidden(k4_tarski(C, E), B) => r2_hidden(k4_tarski(D, E), B)) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d25_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  (m4_yellow_6(B, A) =>  (v6_yellow_6(B, A) <=>  (! [C] :  ( ( ~ (v2_struct_0(C))  &  (v4_orders_2(C) &  (v7_waybel_0(C) & l1_waybel_0(C, A)) ) )  =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ~ ( (r2_hidden(C, k6_yellow_6(A)) &  ( ~ (r2_hidden(k4_tarski(C, D), B))  &  (! [E] :  (m2_yellow_6(E, A, C) =>  ~ ( (r2_hidden(E, k6_yellow_6(A)) &  (! [F] :  (m2_yellow_6(F, A, E) =>  ~ (r2_hidden(k4_tarski(F, D), B)) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d26_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  (m4_yellow_6(B, A) =>  (v7_yellow_6(B, A) <=>  (! [C] :  ( ( ~ (v2_struct_0(C))  &  (v4_orders_2(C) &  (v7_waybel_0(C) & l1_waybel_0(C, A)) ) )  =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r2_hidden(k4_tarski(C, D), B) =>  (! [E] :  (m3_yellow_6(E, u1_struct_0(C), A) =>  ( (! [F] :  (m1_subset_1(F, u1_struct_0(C)) => r2_hidden(k4_tarski(k7_yellow_6(u1_struct_0(C), A, E, F), k2_waybel_0(A, C, F)), B)) )  => r2_hidden(k4_tarski(k8_yellow_6(A, C, E), D), B)) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d27_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  (m4_yellow_6(B, A) =>  (! [C] :  ( (v1_pre_topc(C) & l1_pre_topc(C))  =>  (C=k13_yellow_6(A, B) <=>  (u1_struct_0(C)=u1_struct_0(A) & u1_pre_topc(C)=a_2_1_yellow_6(A, B)) ) ) ) ) ) ) ) ).
fof(d28_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  (m4_yellow_6(B, A) =>  (v8_yellow_6(B, A) <=>  (v4_yellow_6(B, A) &  (v5_yellow_6(B, A) &  (v6_yellow_6(B, A) & v7_yellow_6(B, A)) ) ) ) ) ) ) ) ).
fof(d2_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (v4_orders_2(A) <=>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( (r1_orders_2(A, B, C) & r1_orders_2(A, C, D))  => r1_orders_2(A, B, D)) ) ) ) ) ) ) ) ) ) ).
fof(d2_yellow_3, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (l1_orders_2(B) =>  (! [C] :  ( (v1_orders_2(C) & l1_orders_2(C))  =>  (C=k3_yellow_3(A, B) <=>  (u1_struct_0(C)=k2_zfmisc_1(u1_struct_0(A), u1_struct_0(B)) & u1_orders_2(C)=k2_yellow_3(u1_struct_0(A), u1_struct_0(A), u1_struct_0(B), u1_struct_0(B), u1_orders_2(A), u1_orders_2(B))) ) ) ) ) ) ) ) ).
fof(d3_relat_1, axiom,  (! [A] :  (v1_relat_1(A) =>  (! [B] :  (r1_tarski(A, B) <=>  (! [C] :  (! [D] :  (r2_hidden(k4_tarski(C, D), A) => r2_hidden(k4_tarski(C, D), B)) ) ) ) ) ) ) ).
fof(d3_tarski, axiom,  (! [A] :  (! [B] :  (r1_tarski(A, B) <=>  (! [C] :  (r2_hidden(C, A) => r2_hidden(C, B)) ) ) ) ) ).
fof(d4_partfun1, axiom,  (! [A] :  (! [B] :  ( (v1_relat_1(B) & v4_relat_1(B, A))  =>  (v1_partfun1(B, A) <=> k1_relat_1(B)=A) ) ) ) ).
fof(d4_yellow_1, axiom,  (! [A] :  (! [B] :  ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) &  (v1_partfun1(B, A) & v1_yellow_1(B)) ) ) )  =>  (! [C] :  ( (v1_orders_2(C) & l1_orders_2(C))  =>  (C=k5_yellow_1(A, B) <=>  (u1_struct_0(C)=k4_card_3(k12_pralg_1(A, B)) &  (! [D] :  (m1_subset_1(D, u1_struct_0(C)) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(C)) =>  (r2_hidden(D, k4_card_3(k12_pralg_1(A, B))) =>  (r1_orders_2(C, D, E) <=>  (? [F] :  ( (v1_relat_1(F) & v1_funct_1(F))  &  (? [G] :  ( (v1_relat_1(G) & v1_funct_1(G))  &  (F=D &  (G=E &  (! [H] :  ~ ( (r2_hidden(H, A) &  (! [I] :  (l1_orders_2(I) =>  (! [J] :  (m1_subset_1(J, u1_struct_0(I)) =>  (! [K] :  (m1_subset_1(K, u1_struct_0(I)) =>  ~ ( (I=k1_funct_1(B, H) &  (J=k1_funct_1(F, H) &  (K=k1_funct_1(G, H) & r1_orders_2(I, J, K)) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d5_funct_1, axiom,  (! [A] :  ( (v1_relat_1(A) & v1_funct_1(A))  =>  (! [B] :  (B=k2_relat_1(A) <=>  (! [C] :  (r2_hidden(C, B) <=>  (? [D] :  (r2_hidden(D, k1_relat_1(A)) & C=k1_funct_1(A, D)) ) ) ) ) ) ) ) ).
fof(d5_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_orders_2(A))  =>  (v7_waybel_0(A) <=>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (? [D] :  (m1_subset_1(D, u1_struct_0(A)) &  (r1_orders_2(A, B, D) & r1_orders_2(A, C, D)) ) ) ) ) ) ) ) ) ) ).
fof(d6_yellow_6, axiom,  (! [A] :  (l1_struct_0(A) =>  (! [B] :  (l1_waybel_0(B, A) =>  (v1_yellow_6(B, A) <=> v3_funct_1(u1_waybel_0(A, B))) ) ) ) ) ).
fof(d7_yellow_6, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & l1_struct_0(B))  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(B)) =>  (! [D] :  ( (v6_waybel_0(D, B) & l1_waybel_0(D, B))  =>  (D=k3_yellow_6(A, B, C) <=>  (g1_orders_2(u1_struct_0(D), u1_orders_2(D))=g1_orders_2(u1_struct_0(A), u1_orders_2(A)) & r2_funct_2(u1_struct_0(D), u1_struct_0(B), u1_waybel_0(B, D), k8_funcop_1(u1_struct_0(B), u1_struct_0(D), C))) ) ) ) ) ) ) ) ) ) ).
fof(d8_waybel_0, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & l1_waybel_0(B, A))  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(B)) => k2_waybel_0(A, B, C)=k3_funct_2(u1_struct_0(B), u1_struct_0(A), u1_waybel_0(A, B), C)) ) ) ) ) ) ).
fof(d9_relat_1, axiom,  (! [A] :  (v1_relat_1(A) =>  (v2_relat_1(A) <=>  ~ (r2_hidden(k1_xboole_0, k2_relat_1(A))) ) ) ) ).
fof(dt_g1_orders_2, axiom,  (! [A, B] :  (m1_subset_1(B, k1_zfmisc_1(k2_zfmisc_1(A, A))) =>  (v1_orders_2(g1_orders_2(A, B)) & l1_orders_2(g1_orders_2(A, B))) ) ) ).
fof(dt_g1_pre_topc, axiom,  (! [A, B] :  (m1_subset_1(B, k1_zfmisc_1(k1_zfmisc_1(A))) =>  (v1_pre_topc(g1_pre_topc(A, B)) & l1_pre_topc(g1_pre_topc(A, B))) ) ) ).
fof(dt_g1_waybel_0, axiom,  (! [A, B, C, D] :  ( (l1_struct_0(A) &  (m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(B, B))) &  (v1_funct_1(D) &  (v1_funct_2(D, B, u1_struct_0(A)) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(B, u1_struct_0(A))))) ) ) )  =>  (v6_waybel_0(g1_waybel_0(A, B, C, D), A) & l1_waybel_0(g1_waybel_0(A, B, C, D), A)) ) ) ).
fof(dt_k10_pralg_1, axiom,  (! [A, B, C] :  ( ( ~ (v1_xboole_0(A))  &  ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) &  (v1_partfun1(B, A) & v2_pralg_1(B)) ) ) )  & m1_subset_1(C, A)) )  => l1_struct_0(k10_pralg_1(A, B, C))) ) ).
fof(dt_k10_yellow_6, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  &  ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) ) )  => m1_subset_1(k10_yellow_6(A, B), k1_zfmisc_1(u1_struct_0(A)))) ) ).
fof(dt_k12_pralg_1, axiom,  (! [A, B] :  ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) &  (v1_partfun1(B, A) & v2_pralg_1(B)) ) ) )  =>  (v1_relat_1(k12_pralg_1(A, B)) &  (v4_relat_1(k12_pralg_1(A, B), A) &  (v1_funct_1(k12_pralg_1(A, B)) & v1_partfun1(k12_pralg_1(A, B), A)) ) ) ) ) ).
fof(dt_k12_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  => m4_yellow_6(k12_yellow_6(A), A)) ) ).
fof(dt_k13_yellow_6, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  & m4_yellow_6(B, A))  =>  (v1_pre_topc(k13_yellow_6(A, B)) & l1_pre_topc(k13_yellow_6(A, B))) ) ) ).
fof(dt_k1_binop_1, axiom, $true).
fof(dt_k1_classes1, axiom, $true).
fof(dt_k1_funct_1, axiom, $true).
fof(dt_k1_partfun1, axiom,  (! [A, B, C, D, E, F] :  ( ( (v1_funct_1(E) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(A, B))))  &  (v1_funct_1(F) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(C, D)))) )  =>  (v1_funct_1(k1_partfun1(A, B, C, D, E, F)) & m1_subset_1(k1_partfun1(A, B, C, D, E, F), k1_zfmisc_1(k2_zfmisc_1(A, D)))) ) ) ).
fof(dt_k1_relat_1, axiom, $true).
fof(dt_k1_relset_1, axiom,  (! [A, B, C] :  (m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B))) => m1_subset_1(k1_relset_1(A, B, C), k1_zfmisc_1(A))) ) ).
fof(dt_k1_xboole_0, axiom, $true).
fof(dt_k1_yellow_3, axiom,  (! [A, B] :  ( (v1_relat_1(A) & v1_relat_1(B))  => v1_relat_1(k1_yellow_3(A, B))) ) ).
fof(dt_k1_yellow_6, axiom, $true).
fof(dt_k1_zfmisc_1, axiom, $true).
fof(dt_k2_binop_1, axiom,  (! [A, B, C, D, E, F] :  ( ( ~ (v1_xboole_0(A))  &  ( ~ (v1_xboole_0(B))  &  ( (v1_funct_1(D) &  (v1_funct_2(D, k2_zfmisc_1(A, B), C) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(A, B), C)))) )  &  (m1_subset_1(E, A) & m1_subset_1(F, B)) ) ) )  => m1_subset_1(k2_binop_1(A, B, C, D, E, F), C)) ) ).
fof(dt_k2_funcop_1, axiom, $true).
fof(dt_k2_pre_topc, axiom,  (! [A, B] :  ( (l1_pre_topc(A) & m1_subset_1(B, k1_zfmisc_1(u1_struct_0(A))))  => m1_subset_1(k2_pre_topc(A, B), k1_zfmisc_1(u1_struct_0(A)))) ) ).
fof(dt_k2_relat_1, axiom, $true).
fof(dt_k2_relset_1, axiom,  (! [A, B, C] :  (m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B))) => m1_subset_1(k2_relset_1(A, B, C), k1_zfmisc_1(B))) ) ).
fof(dt_k2_waybel_0, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ( ~ (v2_struct_0(B))  & l1_waybel_0(B, A))  & m1_subset_1(C, u1_struct_0(B))) )  => m1_subset_1(k2_waybel_0(A, B, C), u1_struct_0(A))) ) ).
fof(dt_k2_yellow_3, axiom,  (! [A, B, C, D, E, F] :  ( (m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(A, B))) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(C, D))))  => m1_subset_1(k2_yellow_3(A, B, C, D, E, F), k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(A, C), k2_zfmisc_1(B, D))))) ) ).
fof(dt_k2_yellow_6, axiom,  (! [A, B, C, D] :  ( ( ~ (v1_xboole_0(A))  &  ( ( ~ (v2_struct_0(B))  & l1_orders_2(B))  &  ( (v1_funct_1(C) &  (v1_funct_2(C, A, u1_struct_0(B)) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, u1_struct_0(B))))) )  & m1_subset_1(D, A)) ) )  => m1_subset_1(k2_yellow_6(A, B, C, D), u1_struct_0(B))) ) ).
fof(dt_k2_zfmisc_1, axiom, $true).
fof(dt_k3_funct_1, axiom, $true).
fof(dt_k3_funct_2, axiom,  (! [A, B, C, D] :  ( ( ~ (v1_xboole_0(A))  &  ( (v1_funct_1(C) &  (v1_funct_2(C, A, B) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  & m1_subset_1(D, A)) )  => m1_subset_1(k3_funct_2(A, B, C, D), B)) ) ).
fof(dt_k3_waybel_3, axiom,  (! [A, B, C] :  ( ( ~ (v1_xboole_0(A))  &  ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) &  (v1_partfun1(B, A) & v1_yellow_1(B)) ) ) )  & m1_subset_1(C, A)) )  => l1_orders_2(k3_waybel_3(A, B, C))) ) ).
fof(dt_k3_yellow_3, axiom,  (! [A, B] :  ( (l1_orders_2(A) & l1_orders_2(B))  =>  (v1_orders_2(k3_yellow_3(A, B)) & l1_orders_2(k3_yellow_3(A, B))) ) ) ).
fof(dt_k3_yellow_6, axiom,  (! [A, B, C] :  ( (l1_orders_2(A) &  ( ( ~ (v2_struct_0(B))  & l1_struct_0(B))  & m1_subset_1(C, u1_struct_0(B))) )  =>  (v6_waybel_0(k3_yellow_6(A, B, C), B) & l1_waybel_0(k3_yellow_6(A, B, C), B)) ) ) ).
fof(dt_k4_card_3, axiom, $true).
fof(dt_k4_tarski, axiom, $true).
fof(dt_k4_waybel_3, axiom,  (! [A, B, C, D] :  ( ( ~ (v1_xboole_0(A))  &  ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) &  (v1_partfun1(B, A) &  (v1_yellow_1(B) & v4_waybel_3(B)) ) ) ) )  &  (m1_subset_1(C, u1_struct_0(k5_yellow_1(A, B))) & m1_subset_1(D, A)) ) )  => m1_subset_1(k4_waybel_3(A, B, C, D), u1_struct_0(k3_waybel_3(A, B, D)))) ) ).
fof(dt_k4_yellow_6, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  & l1_waybel_0(B, A))  => m1_subset_1(k4_yellow_6(A, B), u1_struct_0(A))) ) ).
fof(dt_k5_classes1, axiom, $true).
fof(dt_k5_relat_1, axiom,  (! [A, B] :  ( (v1_relat_1(A) & v1_relat_1(B))  => v1_relat_1(k5_relat_1(A, B))) ) ).
fof(dt_k5_yellow_1, axiom,  (! [A, B] :  ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) &  (v1_partfun1(B, A) & v1_yellow_1(B)) ) ) )  =>  (v1_orders_2(k5_yellow_1(A, B)) & l1_orders_2(k5_yellow_1(A, B))) ) ) ).
fof(dt_k6_yellow_6, axiom, $true).
fof(dt_k7_yellow_3, axiom,  (! [A, B, C, D] :  ( ( ( ~ (v2_struct_0(A))  & l1_orders_2(A))  &  ( ( ~ (v2_struct_0(B))  & l1_orders_2(B))  &  (m1_subset_1(C, u1_struct_0(A)) & m1_subset_1(D, u1_struct_0(B))) ) )  => m1_subset_1(k7_yellow_3(A, B, C, D), u1_struct_0(k3_yellow_3(A, B)))) ) ).
fof(dt_k7_yellow_6, axiom,  (! [A, B, C, D] :  ( ( ~ (v1_xboole_0(A))  &  (l1_struct_0(B) &  (m3_yellow_6(C, A, B) & m1_subset_1(D, A)) ) )  =>  ( ~ (v2_struct_0(k7_yellow_6(A, B, C, D)))  &  (v4_orders_2(k7_yellow_6(A, B, C, D)) &  (v7_waybel_0(k7_yellow_6(A, B, C, D)) & l1_waybel_0(k7_yellow_6(A, B, C, D), B)) ) ) ) ) ).
fof(dt_k8_funcop_1, axiom,  (! [A, B, C] :  ( ( ~ (v1_xboole_0(A))  & m1_subset_1(C, A))  =>  (v1_funct_1(k8_funcop_1(A, B, C)) &  (v1_funct_2(k8_funcop_1(A, B, C), B, A) & m1_subset_1(k8_funcop_1(A, B, C), k1_zfmisc_1(k2_zfmisc_1(B, A)))) ) ) ) ).
fof(dt_k8_yellow_6, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  & m3_yellow_6(C, u1_struct_0(B), A)) )  =>  ( ~ (v2_struct_0(k8_yellow_6(A, B, C)))  &  (v4_orders_2(k8_yellow_6(A, B, C)) &  (v6_waybel_0(k8_yellow_6(A, B, C), A) &  (v7_waybel_0(k8_yellow_6(A, B, C)) & l1_waybel_0(k8_yellow_6(A, B, C), A)) ) ) ) ) ) ).
fof(dt_l1_orders_2, axiom,  (! [A] :  (l1_orders_2(A) => l1_struct_0(A)) ) ).
fof(dt_l1_pre_topc, axiom,  (! [A] :  (l1_pre_topc(A) => l1_struct_0(A)) ) ).
fof(dt_l1_struct_0, axiom, $true).
fof(dt_l1_waybel_0, axiom,  (! [A] :  (l1_struct_0(A) =>  (! [B] :  (l1_waybel_0(B, A) => l1_orders_2(B)) ) ) ) ).
fof(dt_m1_subset_1, axiom, $true).
fof(dt_m2_pboole, axiom,  (! [A, B, C] :  ( ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) & v1_partfun1(B, A)) ) )  &  (v1_relat_1(C) &  (v4_relat_1(C, A) &  (v1_funct_1(C) & v1_partfun1(C, A)) ) ) )  =>  (! [D] :  (m2_pboole(D, A, B, C) =>  (v1_relat_1(D) &  (v4_relat_1(D, A) &  (v1_funct_1(D) & v1_partfun1(D, A)) ) ) ) ) ) ) ).
fof(dt_m2_yellow_6, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) ) )  =>  (! [C] :  (m2_yellow_6(C, A, B) =>  ( ~ (v2_struct_0(C))  &  (v4_orders_2(C) &  (v7_waybel_0(C) & l1_waybel_0(C, A)) ) ) ) ) ) ) ).
fof(dt_m3_yellow_6, axiom,  (! [A, B] :  (l1_struct_0(B) =>  (! [C] :  (m3_yellow_6(C, A, B) =>  (v1_relat_1(C) &  (v4_relat_1(C, A) &  (v1_funct_1(C) & v1_partfun1(C, A)) ) ) ) ) ) ) ).
fof(dt_m4_yellow_6, axiom, $true).
fof(dt_o_3_4_yellow_6, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v6_waybel_0(B, A) &  (v7_waybel_0(B) &  (v1_yellow_6(B, A) & l1_waybel_0(B, A)) ) ) ) )  &  (v4_waybel_3(C) & m3_yellow_6(C, u1_struct_0(B), A)) ) )  => m1_subset_1(o_3_4_yellow_6(A, B, C), u1_struct_0(k5_yellow_1(u1_struct_0(B), C)))) ) ).
fof(dt_u1_orders_2, axiom,  (! [A] :  (l1_orders_2(A) => m1_subset_1(u1_orders_2(A), k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A), u1_struct_0(A))))) ) ).
fof(dt_u1_pre_topc, axiom,  (! [A] :  (l1_pre_topc(A) => m1_subset_1(u1_pre_topc(A), k1_zfmisc_1(k1_zfmisc_1(u1_struct_0(A))))) ) ).
fof(dt_u1_struct_0, axiom, $true).
fof(dt_u1_waybel_0, axiom,  (! [A, B] :  ( (l1_struct_0(A) & l1_waybel_0(B, A))  =>  (v1_funct_1(u1_waybel_0(A, B)) &  (v1_funct_2(u1_waybel_0(A, B), u1_struct_0(B), u1_struct_0(A)) & m1_subset_1(u1_waybel_0(A, B), k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(B), u1_struct_0(A))))) ) ) ) ).
fof(existence_l1_orders_2, axiom,  (? [A] : l1_orders_2(A)) ).
fof(existence_l1_pre_topc, axiom,  (? [A] : l1_pre_topc(A)) ).
fof(existence_l1_struct_0, axiom,  (? [A] : l1_struct_0(A)) ).
fof(existence_l1_waybel_0, axiom,  (! [A] :  (l1_struct_0(A) =>  (? [B] : l1_waybel_0(B, A)) ) ) ).
fof(existence_m1_subset_1, axiom,  (! [A] :  (? [B] : m1_subset_1(B, A)) ) ).
fof(existence_m2_pboole, axiom,  (! [A, B, C] :  ( ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) & v1_partfun1(B, A)) ) )  &  (v1_relat_1(C) &  (v4_relat_1(C, A) &  (v1_funct_1(C) & v1_partfun1(C, A)) ) ) )  =>  (? [D] : m2_pboole(D, A, B, C)) ) ) ).
fof(existence_m2_yellow_6, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) ) )  =>  (? [C] : m2_yellow_6(C, A, B)) ) ) ).
fof(existence_m3_yellow_6, axiom,  (! [A, B] :  (l1_struct_0(B) =>  (? [C] : m3_yellow_6(C, A, B)) ) ) ).
fof(existence_m4_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (? [B] : m4_yellow_6(B, A)) ) ) ).
fof(fraenkel_a_2_1_yellow_6, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(B))  & l1_struct_0(B))  & m4_yellow_6(C, B))  =>  (r2_hidden(A, a_2_1_yellow_6(B, C)) <=>  (? [D] :  (m1_subset_1(D, k1_zfmisc_1(u1_struct_0(B))) &  (A=D &  (! [E] :  (m1_subset_1(E, u1_struct_0(B)) =>  (r2_hidden(E, D) =>  (! [F] :  ( ( ~ (v2_struct_0(F))  &  (v4_orders_2(F) &  (v7_waybel_0(F) & l1_waybel_0(F, B)) ) )  =>  (r2_hidden(k4_tarski(F, E), C) => r1_waybel_0(B, F, D)) ) ) ) ) ) ) ) ) ) ) ) ).
fof(fraenkel_a_3_1_yellow_6, axiom,  (! [A, B, C, D] :  ( ( ( ~ (v2_struct_0(B))  &  (v2_pre_topc(B) & l1_pre_topc(B)) )  &  ( ( ~ (v2_struct_0(C))  &  (v4_orders_2(C) &  (v7_waybel_0(C) & l1_waybel_0(C, B)) ) )  & m1_subset_1(D, u1_struct_0(C))) )  =>  (r2_hidden(A, a_3_1_yellow_6(B, C, D)) <=>  (? [E] :  (m1_subset_1(E, u1_struct_0(C)) &  (A=k2_waybel_0(B, C, E) & r1_orders_2(C, D, E)) ) ) ) ) ) ).
fof(fraenkel_a_4_2_yellow_6, axiom,  (! [A, B, C, D, E] :  ( ( ( ~ (v2_struct_0(B))  & l1_struct_0(B))  &  ( ( ~ (v2_struct_0(C))  &  (v4_orders_2(C) &  (v7_waybel_0(C) & l1_waybel_0(C, B)) ) )  &  (m2_yellow_6(D, B, C) & m1_subset_1(E, u1_struct_0(D))) ) )  =>  (r2_hidden(A, a_4_2_yellow_6(B, C, D, E)) <=>  (? [F] :  (m1_subset_1(F, u1_struct_0(D)) &  (A=k2_waybel_0(B, D, F) & r1_orders_2(D, E, F)) ) ) ) ) ) ).
fof(fraenkel_a_4_3_yellow_6, axiom,  (! [A, B, C, D, E] :  ( ( ( ~ (v2_struct_0(B))  & l1_struct_0(B))  &  ( ( ~ (v2_struct_0(C))  &  (v4_orders_2(C) &  (v7_waybel_0(C) & l1_waybel_0(C, B)) ) )  &  (m2_yellow_6(D, B, C) & m1_subset_1(E, u1_struct_0(D))) ) )  =>  (r2_hidden(A, a_4_3_yellow_6(B, C, D, E)) <=>  (? [F] :  (m1_subset_1(F, u1_struct_0(D)) &  (A=F & r1_orders_2(D, E, F)) ) ) ) ) ) ).
fof(fraenkel_a_5_0_yellow_6, axiom,  (! [A, B, C, D, E, F] :  ( ( ( ~ (v2_struct_0(B))  & l1_struct_0(B))  &  (m4_yellow_6(C, B) &  ( ( ~ (v2_struct_0(D))  &  (v4_orders_2(D) &  (v7_waybel_0(D) & l1_waybel_0(D, k13_yellow_6(B, C))) ) )  &  (m2_yellow_6(E, k13_yellow_6(B, C), D) & m1_subset_1(F, u1_struct_0(E))) ) ) )  =>  (r2_hidden(A, a_5_0_yellow_6(B, C, D, E, F)) <=>  (? [G] :  (m1_subset_1(G, u1_struct_0(E)) &  (A=k2_waybel_0(k13_yellow_6(B, C), E, G) & r1_orders_2(E, F, G)) ) ) ) ) ) ).
fof(free_g1_orders_2, axiom,  (! [A, B] :  (m1_subset_1(B, k1_zfmisc_1(k2_zfmisc_1(A, A))) =>  (! [C, D] :  (g1_orders_2(A, B)=g1_orders_2(C, D) =>  (A=C & B=D) ) ) ) ) ).
fof(free_g1_pre_topc, axiom,  (! [A, B] :  (m1_subset_1(B, k1_zfmisc_1(k1_zfmisc_1(A))) =>  (! [C, D] :  (g1_pre_topc(A, B)=g1_pre_topc(C, D) =>  (A=C & B=D) ) ) ) ) ).
fof(free_g1_waybel_0, axiom,  (! [A, B, C, D] :  ( (l1_struct_0(A) &  (m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(B, B))) &  (v1_funct_1(D) &  (v1_funct_2(D, B, u1_struct_0(A)) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(B, u1_struct_0(A))))) ) ) )  =>  (! [E, F, G, H] :  (g1_waybel_0(A, B, C, D)=g1_waybel_0(E, F, G, H) =>  (A=E &  (B=F &  (C=G & D=H) ) ) ) ) ) ) ).
fof(l15_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_orders_2(A))  =>  (v7_waybel_0(A) <=> v7_waybel_0(g1_orders_2(u1_struct_0(A), u1_orders_2(A)))) ) ) ).
fof(l16_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_orders_2(A))  =>  (v4_orders_2(A) <=> v4_orders_2(g1_orders_2(u1_struct_0(A), u1_orders_2(A)))) ) ) ).
fof(l20_yellow_6, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (l1_orders_2(B) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(B)) =>  (! [F] :  (m1_subset_1(F, u1_struct_0(B)) =>  ( (C=E &  (D=F &  (g1_orders_2(u1_struct_0(A), u1_orders_2(A))=g1_orders_2(u1_struct_0(B), u1_orders_2(B)) & r1_orders_2(A, C, D)) ) )  => r1_orders_2(B, E, F)) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(l53_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & l1_struct_0(B))  =>  (u1_struct_0(A)=u1_struct_0(B) => k6_yellow_6(A)=k6_yellow_6(B)) ) ) ) ) ).
fof(projectivity_k2_pre_topc, axiom,  (! [A, B] :  ( (l1_pre_topc(A) & m1_subset_1(B, k1_zfmisc_1(u1_struct_0(A))))  => k2_pre_topc(A, k2_pre_topc(A, B))=k2_pre_topc(A, B)) ) ).
fof(redefinition_k10_pralg_1, axiom,  (! [A, B, C] :  ( ( ~ (v1_xboole_0(A))  &  ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) &  (v1_partfun1(B, A) & v2_pralg_1(B)) ) ) )  & m1_subset_1(C, A)) )  => k10_pralg_1(A, B, C)=k1_funct_1(B, C)) ) ).
fof(redefinition_k1_partfun1, axiom,  (! [A, B, C, D, E, F] :  ( ( (v1_funct_1(E) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(A, B))))  &  (v1_funct_1(F) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(C, D)))) )  => k1_partfun1(A, B, C, D, E, F)=k5_relat_1(E, F)) ) ).
fof(redefinition_k1_relset_1, axiom,  (! [A, B, C] :  (m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B))) => k1_relset_1(A, B, C)=k1_relat_1(C)) ) ).
fof(redefinition_k2_binop_1, axiom,  (! [A, B, C, D, E, F] :  ( ( ~ (v1_xboole_0(A))  &  ( ~ (v1_xboole_0(B))  &  ( (v1_funct_1(D) &  (v1_funct_2(D, k2_zfmisc_1(A, B), C) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(A, B), C)))) )  &  (m1_subset_1(E, A) & m1_subset_1(F, B)) ) ) )  => k2_binop_1(A, B, C, D, E, F)=k1_binop_1(D, E, F)) ) ).
fof(redefinition_k2_relset_1, axiom,  (! [A, B, C] :  (m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B))) => k2_relset_1(A, B, C)=k2_relat_1(C)) ) ).
fof(redefinition_k2_yellow_3, axiom,  (! [A, B, C, D, E, F] :  ( (m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(A, B))) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(C, D))))  => k2_yellow_3(A, B, C, D, E, F)=k1_yellow_3(E, F)) ) ).
fof(redefinition_k2_yellow_6, axiom,  (! [A, B, C, D] :  ( ( ~ (v1_xboole_0(A))  &  ( ( ~ (v2_struct_0(B))  & l1_orders_2(B))  &  ( (v1_funct_1(C) &  (v1_funct_2(C, A, u1_struct_0(B)) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, u1_struct_0(B))))) )  & m1_subset_1(D, A)) ) )  => k2_yellow_6(A, B, C, D)=k1_funct_1(C, D)) ) ).
fof(redefinition_k3_funct_2, axiom,  (! [A, B, C, D] :  ( ( ~ (v1_xboole_0(A))  &  ( (v1_funct_1(C) &  (v1_funct_2(C, A, B) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  & m1_subset_1(D, A)) )  => k3_funct_2(A, B, C, D)=k1_funct_1(C, D)) ) ).
fof(redefinition_k3_waybel_3, axiom,  (! [A, B, C] :  ( ( ~ (v1_xboole_0(A))  &  ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) &  (v1_partfun1(B, A) & v1_yellow_1(B)) ) ) )  & m1_subset_1(C, A)) )  => k3_waybel_3(A, B, C)=k1_funct_1(B, C)) ) ).
fof(redefinition_k4_waybel_3, axiom,  (! [A, B, C, D] :  ( ( ~ (v1_xboole_0(A))  &  ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) &  (v1_partfun1(B, A) &  (v1_yellow_1(B) & v4_waybel_3(B)) ) ) ) )  &  (m1_subset_1(C, u1_struct_0(k5_yellow_1(A, B))) & m1_subset_1(D, A)) ) )  => k4_waybel_3(A, B, C, D)=k1_funct_1(C, D)) ) ).
fof(redefinition_k7_yellow_3, axiom,  (! [A, B, C, D] :  ( ( ( ~ (v2_struct_0(A))  & l1_orders_2(A))  &  ( ( ~ (v2_struct_0(B))  & l1_orders_2(B))  &  (m1_subset_1(C, u1_struct_0(A)) & m1_subset_1(D, u1_struct_0(B))) ) )  => k7_yellow_3(A, B, C, D)=k4_tarski(C, D)) ) ).
fof(redefinition_k7_yellow_6, axiom,  (! [A, B, C, D] :  ( ( ~ (v1_xboole_0(A))  &  (l1_struct_0(B) &  (m3_yellow_6(C, A, B) & m1_subset_1(D, A)) ) )  => k7_yellow_6(A, B, C, D)=k1_funct_1(C, D)) ) ).
fof(redefinition_k8_funcop_1, axiom,  (! [A, B, C] :  ( ( ~ (v1_xboole_0(A))  & m1_subset_1(C, A))  => k8_funcop_1(A, B, C)=k2_funcop_1(B, C)) ) ).
fof(redefinition_r1_funct_2, axiom,  (! [A, B, C, D, E, F] :  ( ( ~ (v1_xboole_0(B))  &  ( ~ (v1_xboole_0(D))  &  ( (v1_funct_1(E) &  (v1_funct_2(E, A, B) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  &  (v1_funct_1(F) &  (v1_funct_2(F, C, D) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(C, D)))) ) ) ) )  =>  (r1_funct_2(A, B, C, D, E, F) <=> E=F) ) ) ).
fof(redefinition_r2_funct_2, axiom,  (! [A, B, C, D] :  ( ( (v1_funct_1(C) &  (v1_funct_2(C, A, B) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  &  (v1_funct_1(D) &  (v1_funct_2(D, A, B) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(A, B)))) ) )  =>  (r2_funct_2(A, B, C, D) <=> C=D) ) ) ).
fof(reflexivity_r1_funct_2, axiom,  (! [A, B, C, D, E, F] :  ( ( ~ (v1_xboole_0(B))  &  ( ~ (v1_xboole_0(D))  &  ( (v1_funct_1(E) &  (v1_funct_2(E, A, B) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  &  (v1_funct_1(F) &  (v1_funct_2(F, C, D) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(C, D)))) ) ) ) )  => r1_funct_2(A, B, C, D, E, E)) ) ).
fof(reflexivity_r2_funct_2, axiom,  (! [A, B, C, D] :  ( ( (v1_funct_1(C) &  (v1_funct_2(C, A, B) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  &  (v1_funct_1(D) &  (v1_funct_2(D, A, B) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(A, B)))) ) )  => r2_funct_2(A, B, C, C)) ) ).
fof(s1_funct_7__e12_126_4_4__yellow_6, axiom,  (! [A, B, C, D, E, F, G, H] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  &  (m2_yellow_6(C, A, B) &  ( ( ~ (v2_struct_0(D))  &  (v4_orders_2(D) &  (v6_waybel_0(D, A) &  (v7_waybel_0(D) &  (v1_yellow_6(D, A) & l1_waybel_0(D, A)) ) ) ) )  &  ( (v4_waybel_3(E) & m3_yellow_6(E, u1_struct_0(D), A))  &  ( (v1_relat_1(F) &  (v4_relat_1(F, u1_struct_0(D)) &  (v1_funct_1(F) & v1_partfun1(F, u1_struct_0(D))) ) )  &  ( (v1_relat_1(G) &  (v2_relat_1(G) &  (v4_relat_1(G, u1_struct_0(D)) &  (v1_funct_1(G) & v1_partfun1(G, u1_struct_0(D))) ) ) )  & m2_pboole(H, u1_struct_0(D), F, G)) ) ) ) ) ) )  =>  ( (! [I] :  (m1_subset_1(I, u1_struct_0(D)) =>  (! [J] :  (m1_subset_1(J, u1_struct_0(k5_yellow_1(u1_struct_0(D), E))) => r2_hidden(k1_funct_1(k1_funct_1(H, I), k4_waybel_3(u1_struct_0(D), E, J, I)), u1_struct_0(C))) ) ) )  =>  (? [I] :  ( (v1_funct_1(I) &  (v1_funct_2(I, k2_zfmisc_1(u1_struct_0(D), u1_struct_0(k5_yellow_1(u1_struct_0(D), E))), u1_struct_0(C)) & m1_subset_1(I, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(u1_struct_0(D), u1_struct_0(k5_yellow_1(u1_struct_0(D), E))), u1_struct_0(C))))) )  &  (! [J] :  (m1_subset_1(J, u1_struct_0(D)) =>  (! [K] :  (m1_subset_1(K, u1_struct_0(k5_yellow_1(u1_struct_0(D), E))) => k2_binop_1(u1_struct_0(D), u1_struct_0(k5_yellow_1(u1_struct_0(D), E)), u1_struct_0(C), I, J, K)=k1_funct_1(k1_funct_1(H, J), k4_waybel_3(u1_struct_0(D), E, K, J))) ) ) ) ) ) ) ) ) ).
fof(s1_mssubfam__e9_126_4_4__yellow_6, axiom,  (! [A, B, C, D, E, F, G] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  &  (m2_yellow_6(C, A, B) &  ( ( ~ (v2_struct_0(D))  &  (v4_orders_2(D) &  (v6_waybel_0(D, A) &  (v7_waybel_0(D) &  (v1_yellow_6(D, A) & l1_waybel_0(D, A)) ) ) ) )  &  ( (v4_waybel_3(E) & m3_yellow_6(E, u1_struct_0(D), A))  &  ( (v1_relat_1(F) &  (v4_relat_1(F, u1_struct_0(D)) &  (v1_funct_1(F) & v1_partfun1(F, u1_struct_0(D))) ) )  &  (v1_relat_1(G) &  (v2_relat_1(G) &  (v4_relat_1(G, u1_struct_0(D)) &  (v1_funct_1(G) & v1_partfun1(G, u1_struct_0(D))) ) ) ) ) ) ) ) ) )  =>  ( (! [H] :  (r2_hidden(H, u1_struct_0(D)) =>  (! [I] :  ~ ( (r2_hidden(I, k1_funct_1(F, H)) &  (! [J] :  ~ ( (r2_hidden(J, k1_funct_1(G, H)) &  (? [K] :  ( (v1_relat_1(K) & v1_funct_1(K))  &  (? [L] :  (m1_subset_1(L, u1_struct_0(D)) &  (k1_funct_1(K, I)=J &  (L=H & k1_funct_1(u1_waybel_0(A, k7_yellow_6(u1_struct_0(D), A, E, L)), I)=k1_funct_1(u1_waybel_0(A, C), J)) ) ) ) ) ) ) ) ) ) ) ) ) )  =>  (? [H] :  (m2_pboole(H, u1_struct_0(D), F, G) &  (! [I] :  ~ ( (r2_hidden(I, u1_struct_0(D)) &  (! [J] :  ( (v1_funct_1(J) &  (v1_funct_2(J, k1_funct_1(F, I), k1_funct_1(G, I)) & m1_subset_1(J, k1_zfmisc_1(k2_zfmisc_1(k1_funct_1(F, I), k1_funct_1(G, I))))) )  =>  ~ ( (J=k1_funct_1(H, I) &  (! [M] :  (r2_hidden(M, k1_funct_1(F, I)) =>  (? [N] :  ( (v1_relat_1(N) & v1_funct_1(N))  &  (? [O] :  (m1_subset_1(O, u1_struct_0(D)) &  (k1_funct_1(N, M)=k1_funct_1(J, M) &  (O=I & k1_funct_1(u1_waybel_0(A, k7_yellow_6(u1_struct_0(D), A, E, O)), M)=k1_funct_1(u1_waybel_0(A, C), k1_funct_1(J, M))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(s3_funct_2__e9_126_4_4_2__yellow_6, axiom,  (! [A, B, C, D, E, F, G] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  &  (m2_yellow_6(C, A, B) &  ( ( ~ (v2_struct_0(D))  &  (v4_orders_2(D) &  (v6_waybel_0(D, A) &  (v7_waybel_0(D) &  (v1_yellow_6(D, A) & l1_waybel_0(D, A)) ) ) ) )  &  ( (v1_relat_1(E) &  (v2_relat_1(E) &  (v4_relat_1(E, u1_struct_0(D)) &  (v1_funct_1(E) & v1_partfun1(E, u1_struct_0(D))) ) ) )  &  ( ( ~ (v2_struct_0(F))  &  (v4_orders_2(F) &  (v7_waybel_0(F) & l1_waybel_0(F, A)) ) )  & m1_subset_1(G, u1_struct_0(D))) ) ) ) ) )  =>  ( (! [H] :  (m1_subset_1(H, u1_struct_0(F)) =>  (? [I] :  (m1_subset_1(I, k1_funct_1(E, G)) & k1_funct_1(u1_waybel_0(A, F), H)=k1_funct_1(u1_waybel_0(A, C), I)) ) ) )  =>  (? [H] :  ( (v1_funct_1(H) &  (v1_funct_2(H, u1_struct_0(F), k1_funct_1(E, G)) & m1_subset_1(H, k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(F), k1_funct_1(E, G))))) )  &  (! [I] :  (m1_subset_1(I, u1_struct_0(F)) => k1_funct_1(u1_waybel_0(A, F), I)=k1_funct_1(u1_waybel_0(A, C), k3_funct_2(u1_struct_0(F), k1_funct_1(E, G), H, I))) ) ) ) ) ) ) ).
fof(s3_pboole__e21_126_4__yellow_6, axiom,  (! [A, B, C, D, E, F] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  (m4_yellow_6(B, A) &  (m1_subset_1(C, u1_struct_0(k13_yellow_6(A, B))) &  ( ( ~ (v2_struct_0(D))  &  (v4_orders_2(D) &  (v7_waybel_0(D) & l1_waybel_0(D, A)) ) )  &  (m2_yellow_6(E, A, D) &  ( ~ (v2_struct_0(F))  &  (v4_orders_2(F) &  (v6_waybel_0(F, A) &  (v7_waybel_0(F) &  (v1_yellow_6(F, A) & l1_waybel_0(F, A)) ) ) ) ) ) ) ) ) )  =>  ( (! [G] :  ~ ( (r2_hidden(G, u1_struct_0(F)) &  (! [H] :  ~ ( (? [I] :  (m1_subset_1(I, u1_struct_0(E)) &  (? [J] :  ( ( ~ (v2_struct_0(J))  &  (v4_orders_2(J) &  (v7_waybel_0(J) & l1_waybel_0(J, A)) ) )  &  (G=I &  (J=H &  (r2_hidden(k4_tarski(J, C), B) & r1_tarski(k2_relset_1(u1_struct_0(J), u1_struct_0(A), u1_waybel_0(A, J)), a_4_2_yellow_6(A, D, E, I))) ) ) ) ) ) ) ) ) ) ) )  =>  (? [G] :  ( (v1_relat_1(G) &  (v4_relat_1(G, u1_struct_0(F)) &  (v1_funct_1(G) & v1_partfun1(G, u1_struct_0(F))) ) )  &  (! [H] :  (r2_hidden(H, u1_struct_0(F)) =>  (? [K] :  (m1_subset_1(K, u1_struct_0(E)) &  (? [L] :  ( ( ~ (v2_struct_0(L))  &  (v4_orders_2(L) &  (v7_waybel_0(L) & l1_waybel_0(L, A)) ) )  &  (H=K &  (L=k1_funct_1(G, H) &  (r2_hidden(k4_tarski(L, C), B) & r1_tarski(k2_relset_1(u1_struct_0(L), u1_struct_0(A), u1_waybel_0(A, L)), a_4_2_yellow_6(A, D, E, K))) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(s5_pboole__e1_126_4_4__yellow_6, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  & m2_yellow_6(C, A, B)) )  =>  (? [D] :  ( (v1_relat_1(D) &  (v4_relat_1(D, u1_struct_0(C)) &  (v1_funct_1(D) & v1_partfun1(D, u1_struct_0(C))) ) )  &  (! [E] :  (m1_subset_1(E, u1_struct_0(C)) => k1_funct_1(D, E)=a_4_3_yellow_6(A, B, C, E)) ) ) ) ) ) ).
fof(s5_pboole__e5_126_4_4__yellow_6, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v6_waybel_0(B, A) &  (v7_waybel_0(B) &  (v1_yellow_6(B, A) & l1_waybel_0(B, A)) ) ) ) )  &  (v4_waybel_3(C) & m3_yellow_6(C, u1_struct_0(B), A)) ) )  =>  (? [D] :  ( (v1_relat_1(D) &  (v4_relat_1(D, u1_struct_0(B)) &  (v1_funct_1(D) & v1_partfun1(D, u1_struct_0(B))) ) )  &  (! [E] :  (m1_subset_1(E, u1_struct_0(B)) => k1_funct_1(D, E)=u1_struct_0(k7_yellow_6(u1_struct_0(B), A, C, E))) ) ) ) ) ) ).
fof(s7_domain_1__e3_126_4_4_3__yellow_6, axiom,  (! [A, B, C, D] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  &  (m2_yellow_6(C, A, B) & m1_subset_1(D, u1_struct_0(C))) ) )  => m1_subset_1(a_4_3_yellow_6(A, B, C, D), k1_zfmisc_1(u1_struct_0(C)))) ) ).
fof(symmetry_r1_funct_2, axiom,  (! [A, B, C, D, E, F] :  ( ( ~ (v1_xboole_0(B))  &  ( ~ (v1_xboole_0(D))  &  ( (v1_funct_1(E) &  (v1_funct_2(E, A, B) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  &  (v1_funct_1(F) &  (v1_funct_2(F, C, D) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(C, D)))) ) ) ) )  =>  (r1_funct_2(A, B, C, D, E, F) => r1_funct_2(A, B, C, D, F, E)) ) ) ).
fof(symmetry_r2_funct_2, axiom,  (! [A, B, C, D] :  ( ( (v1_funct_1(C) &  (v1_funct_2(C, A, B) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  &  (v1_funct_1(D) &  (v1_funct_2(D, A, B) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(A, B)))) ) )  =>  (r2_funct_2(A, B, C, D) => r2_funct_2(A, B, D, C)) ) ) ).
fof(t106_zfmisc_1, axiom,  (! [A] :  (! [B] :  (! [C] :  (! [D] :  (r2_hidden(k4_tarski(A, B), k2_zfmisc_1(C, D)) <=>  (r2_hidden(A, C) & r2_hidden(B, D)) ) ) ) ) ) ).
fof(t11_yellow_3, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_orders_2(A))  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & l1_orders_2(B))  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(B)) =>  (! [F] :  (m1_subset_1(F, u1_struct_0(B)) =>  ( (r1_orders_2(A, C, D) & r1_orders_2(B, E, F))  <=> r1_orders_2(k3_yellow_3(A, B), k7_yellow_3(A, B, C, E), k7_yellow_3(A, B, D, F))) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t13_yellow_6, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & l1_struct_0(B))  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(B)) => u1_struct_0(k3_yellow_6(A, B, C))=u1_struct_0(A)) ) ) ) ) ) ).
fof(t14_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_orders_2(A))  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & l1_struct_0(B))  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(B)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(k3_yellow_6(A, B, C))) => k2_waybel_0(B, k3_yellow_6(A, B, C), D)=C) ) ) ) ) ) ) ) ).
fof(t18_card_3, axiom,  (! [A] :  ( (v1_relat_1(A) & v1_funct_1(A))  =>  (! [B] :  ( (v1_relat_1(B) & v1_funct_1(B))  =>  (r2_hidden(A, k4_card_3(B)) <=>  (k1_relat_1(A)=k1_relat_1(B) &  (! [C] :  (r2_hidden(C, k1_relat_1(B)) => r2_hidden(k1_funct_1(A, C), k1_funct_1(B, C))) ) ) ) ) ) ) ) ).
fof(t1_subset, axiom,  (! [A] :  (! [B] :  (r2_hidden(A, B) => m1_subset_1(A, B)) ) ) ).
fof(t20_funct_1, axiom,  (! [A] :  ( (v1_relat_1(A) & v1_funct_1(A))  =>  (! [B] :  ( (v1_relat_1(B) & v1_funct_1(B))  =>  (! [C] :  ( (v1_relat_1(C) & v1_funct_1(C))  =>  ( ( (! [D] :  (r2_hidden(D, k1_relat_1(C)) <=>  (r2_hidden(D, k1_relat_1(A)) & r2_hidden(k1_funct_1(A, D), k1_relat_1(B))) ) )  &  (! [D] :  (r2_hidden(D, k1_relat_1(C)) => k1_funct_1(C, D)=k1_funct_1(B, k1_funct_1(A, D))) ) )  => C=k5_relat_1(A, B)) ) ) ) ) ) ) ).
fof(t22_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_orders_2(A))  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & l1_struct_0(B))  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(B)) => k4_yellow_6(B, k3_yellow_6(A, B, C))=C) ) ) ) ) ) ).
fof(t2_subset, axiom,  (! [A] :  (! [B] :  (m1_subset_1(A, B) =>  (v1_xboole_0(B) | r2_hidden(A, B)) ) ) ) ).
fof(t2_tarski, axiom,  (! [A] :  (! [B] :  ( (! [C] :  (r2_hidden(C, A) <=> r2_hidden(C, B)) )  => A=B) ) ) ).
fof(t33_yellow_6, axiom,  (! [A] :  (! [B] :  (l1_struct_0(B) =>  (! [C] :  ( (v1_relat_1(C) &  (v4_relat_1(C, A) &  (v1_funct_1(C) & v1_partfun1(C, A)) ) )  =>  (m3_yellow_6(C, A, B) <=>  (! [D] :  (r2_hidden(D, A) =>  ( ~ (v2_struct_0(k1_funct_1(C, D)))  &  (v4_orders_2(k1_funct_1(C, D)) &  (v7_waybel_0(k1_funct_1(C, D)) & l1_waybel_0(k1_funct_1(C, D), B)) ) ) ) ) ) ) ) ) ) ) ).
fof(t35_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  =>  (! [C] :  (m3_yellow_6(C, u1_struct_0(B), A) => u1_struct_0(k8_yellow_6(A, B, C))=k2_zfmisc_1(u1_struct_0(B), k4_card_3(k12_pralg_1(u1_struct_0(B), C)))) ) ) ) ) ) ).
fof(t36_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  =>  (! [C] :  (m3_yellow_6(C, u1_struct_0(B), A) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(B)) =>  (! [E] :  (m1_subset_1(E, u1_struct_0(k5_yellow_1(u1_struct_0(B), C))) =>  (! [F] :  (m1_subset_1(F, u1_struct_0(k8_yellow_6(A, B, C))) =>  (F=k7_yellow_3(B, k5_yellow_1(u1_struct_0(B), C), D, E) => k2_waybel_0(A, k8_yellow_6(A, B, C), F)=k3_funct_2(u1_struct_0(k3_waybel_3(u1_struct_0(B), C, D)), u1_struct_0(A), u1_waybel_0(A, k7_yellow_6(u1_struct_0(B), A, C, D)), k4_waybel_3(u1_struct_0(B), C, E, D))) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t3_subset, axiom,  (! [A] :  (! [B] :  (m1_subset_1(A, k1_zfmisc_1(B)) <=> r1_tarski(A, B)) ) ) ).
fof(t41_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  =>  (! [C] :  (m2_yellow_6(C, A, B) => r1_tarski(k10_yellow_6(A, B), k10_yellow_6(A, C))) ) ) ) ) ) ).
fof(t43_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r2_hidden(C, k10_yellow_6(A, B)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(B)) =>  (? [E] :  (m1_subset_1(E, k1_zfmisc_1(u1_struct_0(A))) &  (E=a_3_1_yellow_6(A, B, D) & r2_hidden(C, k2_pre_topc(A, E))) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t49_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  (m4_yellow_6(B, A) => r1_tarski(B, k12_yellow_6(k13_yellow_6(A, B)))) ) ) ) ).
fof(t4_subset, axiom,  (! [A] :  (! [B] :  (! [C] :  ( (r2_hidden(A, B) & m1_subset_1(B, k1_zfmisc_1(C)))  => m1_subset_1(A, C)) ) ) ) ).
fof(t52_yellow_6, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  ( (v8_yellow_6(B, A) & m4_yellow_6(B, A))  =>  (! [C] :  (m1_subset_1(C, k1_zfmisc_1(u1_struct_0(k13_yellow_6(A, B)))) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(k13_yellow_6(A, B))) =>  ~ ( (r2_hidden(D, k2_pre_topc(k13_yellow_6(A, B), C)) &  (! [E] :  ( ( ~ (v2_struct_0(E))  &  (v4_orders_2(E) &  (v7_waybel_0(E) & l1_waybel_0(E, k13_yellow_6(A, B))) ) )  =>  ~ ( (r2_hidden(k4_tarski(E, D), B) &  (r1_tarski(k2_relset_1(u1_struct_0(E), u1_struct_0(k13_yellow_6(A, B)), u1_waybel_0(k13_yellow_6(A, B), E)), C) & r2_hidden(D, k10_yellow_6(k13_yellow_6(A, B), E))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t5_subset, axiom,  (! [A] :  (! [B] :  (! [C] :  ~ ( (r2_hidden(A, B) &  (m1_subset_1(B, k1_zfmisc_1(C)) & v1_xboole_0(C)) ) ) ) ) ) ).
fof(t6_boole, axiom,  (! [A] :  (v1_xboole_0(A) => A=k1_xboole_0) ) ).
fof(t7_boole, axiom,  (! [A] :  (! [B] :  ~ ( (r2_hidden(A, B) & v1_xboole_0(B)) ) ) ) ).
fof(t7_funct_2, axiom,  (! [A] :  (! [B] :  (! [C] :  (! [D] :  ( (v1_funct_1(D) &  (v1_funct_2(D, A, B) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  =>  (r2_hidden(C, A) =>  (B=k1_xboole_0 | r2_hidden(k1_funct_1(D, C), B)) ) ) ) ) ) ) ).
fof(t8_boole, axiom,  (! [A] :  (! [B] :  ~ ( (v1_xboole_0(A) &  ( ~ (A=B)  & v1_xboole_0(B)) ) ) ) ) ).
fof(t9_domain_1, axiom,  (! [A] :  (! [B] :  ( ~ (v1_xboole_0(B))  =>  (! [C] :  ( ~ (v1_xboole_0(C))  =>  ~ ( (r2_hidden(A, k2_zfmisc_1(B, C)) &  (! [D] :  (m1_subset_1(D, B) =>  (! [E] :  (m1_subset_1(E, C) =>  ~ (A=k4_tarski(D, E)) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t9_funct_1, axiom,  (! [A] :  ( (v1_relat_1(A) & v1_funct_1(A))  =>  (! [B] :  ( (v1_relat_1(B) & v1_funct_1(B))  =>  ( (k1_relat_1(A)=k1_relat_1(B) &  (! [C] :  (r2_hidden(C, k1_relat_1(A)) => k1_funct_1(A, C)=k1_funct_1(B, C)) ) )  => A=B) ) ) ) ) ).
fof(t9_yellow_6, axiom,  (! [A] :  ( ~ (v1_xboole_0(A))  =>  (! [B] :  ( (v1_relat_1(B) &  (v4_relat_1(B, A) &  (v1_funct_1(B) &  (v1_partfun1(B, A) & v2_pralg_1(B)) ) ) )  =>  (! [C] :  (m1_subset_1(C, A) => k1_funct_1(k12_pralg_1(A, B), C)=u1_struct_0(k10_pralg_1(A, B, C))) ) ) ) ) ) ).
