fof(l19_lattices, conjecture,  (! [A] :  ( (v1_funct_1(A) &  (v1_funct_2(A, k2_zfmisc_1(k1_zfmisc_1(k1_xboole_0), k1_zfmisc_1(k1_xboole_0)), k1_zfmisc_1(k1_xboole_0)) & m1_subset_1(A, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(k1_zfmisc_1(k1_xboole_0), k1_zfmisc_1(k1_xboole_0)), k1_zfmisc_1(k1_xboole_0))))) )  =>  (! [B] :  ( (v1_funct_1(B) &  (v1_funct_2(B, k2_zfmisc_1(k1_zfmisc_1(k1_xboole_0), k1_zfmisc_1(k1_xboole_0)), k1_zfmisc_1(k1_xboole_0)) & m1_subset_1(B, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(k1_zfmisc_1(k1_xboole_0), k1_zfmisc_1(k1_xboole_0)), k1_zfmisc_1(k1_xboole_0))))) )  =>  ( ~ (v2_struct_0(g3_lattices(k1_zfmisc_1(k1_xboole_0), A, B)))  &  (v10_lattices(g3_lattices(k1_zfmisc_1(k1_xboole_0), A, B)) &  (v13_lattices(g3_lattices(k1_zfmisc_1(k1_xboole_0), A, B)) & l3_lattices(g3_lattices(k1_zfmisc_1(k1_xboole_0), A, B))) ) ) ) ) ) ) ).
fof(abstractness_v3_lattices, axiom,  (! [A] :  (l3_lattices(A) =>  (v3_lattices(A) => A=g3_lattices(u1_struct_0(A), u2_lattices(A), u1_lattices(A))) ) ) ).
fof(cc1_subset_1, axiom,  (! [A] :  (v1_xboole_0(A) =>  (! [B] :  (m1_subset_1(B, k1_zfmisc_1(A)) => v1_xboole_0(B)) ) ) ) ).
fof(d13_lattices, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_lattices(A))  =>  (v13_lattices(A) <=>  (? [B] :  (m1_subset_1(B, u1_struct_0(A)) &  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (k2_lattices(A, B, C)=B & k2_lattices(A, C, B)=B) ) ) ) ) ) ) ) ).
fof(dt_k2_lattices, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  & l1_lattices(A))  &  (m1_subset_1(B, u1_struct_0(A)) & m1_subset_1(C, u1_struct_0(A))) )  => m1_subset_1(k2_lattices(A, B, C), u1_struct_0(A))) ) ).
fof(dt_l3_lattices, axiom,  (! [A] :  (l3_lattices(A) =>  (l1_lattices(A) & l2_lattices(A)) ) ) ).
fof(fc1_subset_1, axiom,  (! [A] :  ~ (v1_xboole_0(k1_zfmisc_1(A))) ) ).
fof(fc1_xboole_0, axiom, v1_xboole_0(k1_xboole_0)).
fof(fc3_lattices, axiom,  (! [A, B, C] :  ( ( ~ (v1_xboole_0(A))  &  ( (v1_funct_1(B) &  (v1_funct_2(B, k2_zfmisc_1(A, A), A) & m1_subset_1(B, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(A, A), A)))) )  &  (v1_funct_1(C) &  (v1_funct_2(C, k2_zfmisc_1(A, A), A) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(A, A), A)))) ) ) )  =>  ( ~ (v2_struct_0(g3_lattices(A, B, C)))  & v3_lattices(g3_lattices(A, B, C))) ) ) ).
fof(free_g3_lattices, axiom,  (! [A, B, C] :  ( ( (v1_funct_1(B) &  (v1_funct_2(B, k2_zfmisc_1(A, A), A) & m1_subset_1(B, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(A, A), A)))) )  &  (v1_funct_1(C) &  (v1_funct_2(C, k2_zfmisc_1(A, A), A) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(A, A), A)))) ) )  =>  (! [D, E, F] :  (g3_lattices(A, B, C)=g3_lattices(D, E, F) =>  (A=D &  (B=E & C=F) ) ) ) ) ) ).
fof(l18_lattices, axiom,  (! [A] :  ( (v1_funct_1(A) &  (v1_funct_2(A, k2_zfmisc_1(k1_zfmisc_1(k1_xboole_0), k1_zfmisc_1(k1_xboole_0)), k1_zfmisc_1(k1_xboole_0)) & m1_subset_1(A, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(k1_zfmisc_1(k1_xboole_0), k1_zfmisc_1(k1_xboole_0)), k1_zfmisc_1(k1_xboole_0))))) )  =>  (! [B] :  ( (v1_funct_1(B) &  (v1_funct_2(B, k2_zfmisc_1(k1_zfmisc_1(k1_xboole_0), k1_zfmisc_1(k1_xboole_0)), k1_zfmisc_1(k1_xboole_0)) & m1_subset_1(B, k1_zfmisc_1(k2_zfmisc_1(k2_zfmisc_1(k1_zfmisc_1(k1_xboole_0), k1_zfmisc_1(k1_xboole_0)), k1_zfmisc_1(k1_xboole_0))))) )  =>  ( ~ (v2_struct_0(g3_lattices(k1_zfmisc_1(k1_xboole_0), A, B)))  &  (v10_lattices(g3_lattices(k1_zfmisc_1(k1_xboole_0), A, B)) & l3_lattices(g3_lattices(k1_zfmisc_1(k1_xboole_0), A, B))) ) ) ) ) ) ).
fof(rc2_subset_1, axiom,  (! [A] :  (? [B] :  (m1_subset_1(B, k1_zfmisc_1(A)) & v1_xboole_0(B)) ) ) ).
fof(t6_boole, axiom,  (! [A] :  (v1_xboole_0(A) => A=k1_xboole_0) ) ).
