fof(t109_tmap_1, conjecture,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (v1_funct_1(k2_tmap_1(A, k8_tmap_1(A, B), k9_tmap_1(A, B), B)) &  (v1_funct_2(k2_tmap_1(A, k8_tmap_1(A, B), k9_tmap_1(A, B), B), u1_struct_0(B), u1_struct_0(k8_tmap_1(A, B))) &  (v5_pre_topc(k2_tmap_1(A, k8_tmap_1(A, B), k9_tmap_1(A, B), B), B, k8_tmap_1(A, B)) & m1_subset_1(k2_tmap_1(A, k8_tmap_1(A, B), k9_tmap_1(A, B), B), k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(B), u1_struct_0(k8_tmap_1(A, B)))))) ) ) ) ) ) ) ).
fof(cc1_pre_topc, axiom,  (! [A] :  ( (v2_pre_topc(A) & l1_pre_topc(A))  =>  (! [B] :  (m1_pre_topc(B, A) => v2_pre_topc(B)) ) ) ) ).
fof(dt_k2_tmap_1, axiom,  (! [A, B, C, D] :  ( (l1_struct_0(A) &  (l1_struct_0(B) &  ( (v1_funct_1(C) &  (v1_funct_2(C, u1_struct_0(A), u1_struct_0(B)) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A), u1_struct_0(B))))) )  & l1_struct_0(D)) ) )  =>  (v1_funct_1(k2_tmap_1(A, B, C, D)) &  (v1_funct_2(k2_tmap_1(A, B, C, D), u1_struct_0(D), u1_struct_0(B)) & m1_subset_1(k2_tmap_1(A, B, C, D), k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(D), u1_struct_0(B))))) ) ) ) ).
fof(dt_k8_tmap_1, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  & m1_pre_topc(B, A))  =>  (v1_pre_topc(k8_tmap_1(A, B)) &  (v2_pre_topc(k8_tmap_1(A, B)) & l1_pre_topc(k8_tmap_1(A, B))) ) ) ) ).
fof(dt_k9_tmap_1, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  & m1_pre_topc(B, A))  =>  (v1_funct_1(k9_tmap_1(A, B)) &  (v1_funct_2(k9_tmap_1(A, B), u1_struct_0(A), u1_struct_0(k8_tmap_1(A, B))) & m1_subset_1(k9_tmap_1(A, B), k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A), u1_struct_0(k8_tmap_1(A, B)))))) ) ) ) ).
fof(dt_l1_pre_topc, axiom,  (! [A] :  (l1_pre_topc(A) => l1_struct_0(A)) ) ).
fof(dt_m1_pre_topc, axiom,  (! [A] :  (l1_pre_topc(A) =>  (! [B] :  (m1_pre_topc(B, A) => l1_pre_topc(B)) ) ) ) ).
fof(fc5_tmap_1, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  & m1_pre_topc(B, A))  =>  ( ~ (v2_struct_0(k8_tmap_1(A, B)))  &  (v1_pre_topc(k8_tmap_1(A, B)) & v2_pre_topc(k8_tmap_1(A, B))) ) ) ) ).
fof(t107_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(B)) => r1_tmap_1(B, k8_tmap_1(A, B), k2_tmap_1(A, k8_tmap_1(A, B), k9_tmap_1(A, B), B), C)) ) ) ) ) ) ).
fof(t44_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v2_pre_topc(B) & l1_pre_topc(B)) )  =>  (! [C] :  ( (v1_funct_1(C) &  (v1_funct_2(C, u1_struct_0(B), u1_struct_0(A)) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(B), u1_struct_0(A))))) )  =>  (v5_pre_topc(C, B, A) <=>  (! [D] :  (m1_subset_1(D, u1_struct_0(B)) => r1_tmap_1(B, A, C, D)) ) ) ) ) ) ) ) ) ).
