fof(t125_tmap_1, conjecture,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (A=k1_tsep_1(A, B, C) =>  (r3_tsep_1(A, B, C) <=>  (r1_tsep_1(B, C) &  (! [D] :  ( ( ~ (v2_struct_0(D))  &  (v2_pre_topc(D) & l1_pre_topc(D)) )  =>  (! [E] :  ( (v1_funct_1(E) &  (v1_funct_2(E, u1_struct_0(A), u1_struct_0(D)) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A), u1_struct_0(D))))) )  =>  ( ( (v1_funct_1(k2_tmap_1(A, D, E, B)) &  (v1_funct_2(k2_tmap_1(A, D, E, B), u1_struct_0(B), u1_struct_0(D)) &  (v5_pre_topc(k2_tmap_1(A, D, E, B), B, D) & m1_subset_1(k2_tmap_1(A, D, E, B), k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(B), u1_struct_0(D))))) ) )  &  (v1_funct_1(k2_tmap_1(A, D, E, C)) &  (v1_funct_2(k2_tmap_1(A, D, E, C), u1_struct_0(C), u1_struct_0(D)) &  (v5_pre_topc(k2_tmap_1(A, D, E, C), C, D) & m1_subset_1(k2_tmap_1(A, D, E, C), k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(C), u1_struct_0(D))))) ) ) )  =>  (v1_funct_1(E) &  (v1_funct_2(E, u1_struct_0(A), u1_struct_0(D)) &  (v5_pre_topc(E, A, D) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A), u1_struct_0(D))))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(cc1_relset_1, axiom,  (! [A, B] :  (! [C] :  (m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B))) => v1_relat_1(C)) ) ) ).
fof(cc2_relset_1, axiom,  (! [A, B] :  (! [C] :  (m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B))) =>  (v4_relat_1(C, A) & v5_relat_1(C, B)) ) ) ) ).
fof(d4_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v2_pre_topc(B) & l1_pre_topc(B)) )  =>  (! [C] :  ( (v1_funct_1(C) &  (v1_funct_2(C, u1_struct_0(A), u1_struct_0(B)) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A), u1_struct_0(B))))) )  =>  (! [D] :  (m1_pre_topc(D, A) => k2_tmap_1(A, B, C, D)=k2_partfun1(u1_struct_0(A), u1_struct_0(B), C, u1_struct_0(D))) ) ) ) ) ) ) ) ).
fof(dt_k1_tsep_1, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  & l1_pre_topc(A))  &  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  &  ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A)) ) )  =>  ( ~ (v2_struct_0(k1_tsep_1(A, B, C)))  &  (v1_pre_topc(k1_tsep_1(A, B, C)) & m1_pre_topc(k1_tsep_1(A, B, C), A)) ) ) ) ).
fof(dt_k2_tmap_1, axiom,  (! [A, B, C, D] :  ( (l1_struct_0(A) &  (l1_struct_0(B) &  ( (v1_funct_1(C) &  (v1_funct_2(C, u1_struct_0(A), u1_struct_0(B)) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A), u1_struct_0(B))))) )  & l1_struct_0(D)) ) )  =>  (v1_funct_1(k2_tmap_1(A, B, C, D)) &  (v1_funct_2(k2_tmap_1(A, B, C, D), u1_struct_0(D), u1_struct_0(B)) & m1_subset_1(k2_tmap_1(A, B, C, D), k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(D), u1_struct_0(B))))) ) ) ) ).
fof(dt_l1_pre_topc, axiom,  (! [A] :  (l1_pre_topc(A) => l1_struct_0(A)) ) ).
fof(fc2_tmap_1, axiom,  (! [A, B, C, D] :  ( ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  &  ( ( ~ (v2_struct_0(B))  &  (v2_pre_topc(B) & l1_pre_topc(B)) )  &  ( (v1_funct_1(C) &  (v1_funct_2(C, u1_struct_0(A), u1_struct_0(B)) &  (v5_pre_topc(C, A, B) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A), u1_struct_0(B))))) ) )  &  ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A)) ) ) )  =>  (v1_funct_1(k2_tmap_1(A, B, C, D)) &  (v1_funct_2(k2_tmap_1(A, B, C, D), u1_struct_0(D), u1_struct_0(B)) & v5_pre_topc(k2_tmap_1(A, B, C, D), D, B)) ) ) ) ).
fof(rd8_relat_1, axiom,  (! [A, B] :  ( (v1_relat_1(B) & v4_relat_1(B, A))  => k5_relat_1(B, A)=B) ) ).
fof(redefinition_k2_partfun1, axiom,  (! [A, B, C, D] :  ( (v1_funct_1(C) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B))))  => k2_partfun1(A, B, C, D)=k5_relat_1(C, D)) ) ).
fof(t124_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (r3_tsep_1(A, B, C) <=>  (r1_tsep_1(B, C) &  (! [D] :  ( ( ~ (v2_struct_0(D))  &  (v2_pre_topc(D) & l1_pre_topc(D)) )  =>  (! [E] :  ( (v1_funct_1(E) &  (v1_funct_2(E, u1_struct_0(A), u1_struct_0(D)) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(A), u1_struct_0(D))))) )  =>  ( ( (v1_funct_1(k2_tmap_1(A, D, E, B)) &  (v1_funct_2(k2_tmap_1(A, D, E, B), u1_struct_0(B), u1_struct_0(D)) &  (v5_pre_topc(k2_tmap_1(A, D, E, B), B, D) & m1_subset_1(k2_tmap_1(A, D, E, B), k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(B), u1_struct_0(D))))) ) )  &  (v1_funct_1(k2_tmap_1(A, D, E, C)) &  (v1_funct_2(k2_tmap_1(A, D, E, C), u1_struct_0(C), u1_struct_0(D)) &  (v5_pre_topc(k2_tmap_1(A, D, E, C), C, D) & m1_subset_1(k2_tmap_1(A, D, E, C), k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(C), u1_struct_0(D))))) ) ) )  =>  (v1_funct_1(k2_tmap_1(A, D, E, k1_tsep_1(A, B, C))) &  (v1_funct_2(k2_tmap_1(A, D, E, k1_tsep_1(A, B, C)), u1_struct_0(k1_tsep_1(A, B, C)), u1_struct_0(D)) &  (v5_pre_topc(k2_tmap_1(A, D, E, k1_tsep_1(A, B, C)), k1_tsep_1(A, B, C), D) & m1_subset_1(k2_tmap_1(A, D, E, k1_tsep_1(A, B, C)), k1_zfmisc_1(k2_zfmisc_1(u1_struct_0(k1_tsep_1(A, B, C)), u1_struct_0(D))))) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
