fof(t12_partfun2, conjecture,  (! [A] :  ( ~ (v1_xboole_0(A))  =>  (! [B] :  ( ~ (v1_xboole_0(B))  =>  (! [C] :  (m1_subset_1(C, A) =>  (! [D] :  ( (v1_funct_1(D) &  (v2_funct_1(D) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  =>  (r2_hidden(C, k1_relset_1(A, D)) =>  (C=k7_partfun1(A, k2_partfun2(A, B, D), k7_partfun1(B, D, C)) & C=k7_partfun1(A, k1_partfun1(A, B, B, A, D, k2_partfun2(A, B, D)), C)) ) ) ) ) ) ) ) ) ) ).
fof(cc1_relset_1, axiom,  (! [A, B] :  (! [C] :  (m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B))) => v1_relat_1(C)) ) ) ).
fof(cc2_relset_1, axiom,  (! [A, B] :  (! [C] :  (m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B))) =>  (v4_relat_1(C, A) & v5_relat_1(C, B)) ) ) ) ).
fof(dt_k2_partfun2, axiom,  (! [A, B, C] :  ( (v1_funct_1(C) &  (v2_funct_1(C) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  =>  (v1_funct_1(k2_partfun2(A, B, C)) & m1_subset_1(k2_partfun2(A, B, C), k1_zfmisc_1(k2_zfmisc_1(B, A)))) ) ) ).
fof(dt_k7_partfun1, axiom,  (! [A, B, C] :  ( (v1_relat_1(B) &  (v5_relat_1(B, A) & v1_funct_1(B)) )  => m1_subset_1(k7_partfun1(A, B, C), A)) ) ).
fof(redefinition_k2_partfun2, axiom,  (! [A, B, C] :  ( (v1_funct_1(C) &  (v2_funct_1(C) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  => k2_partfun2(A, B, C)=k2_funct_1(C)) ) ).
fof(reflexivity_r2_relset_1, axiom,  (! [A, B, C, D] :  ( (m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B))) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(A, B))))  => r2_relset_1(A, B, C, C)) ) ).
fof(t11_partfun2, axiom,  (! [A] :  ( ~ (v1_xboole_0(A))  =>  (! [B] :  ( ~ (v1_xboole_0(B))  =>  (! [C] :  ( (v1_funct_1(C) &  (v2_funct_1(C) & m1_subset_1(C, k1_zfmisc_1(k2_zfmisc_1(A, B)))) )  =>  (! [D] :  ( (v1_funct_1(D) & m1_subset_1(D, k1_zfmisc_1(k2_zfmisc_1(B, A))))  =>  (r2_relset_1(B, A, D, k2_partfun2(A, B, C)) <=>  (k1_relset_1(B, D)=k2_relset_1(B, C) &  (! [E] :  (m1_subset_1(E, B) =>  (! [F] :  (m1_subset_1(F, A) =>  ( ( (r2_hidden(E, k2_relset_1(B, C)) & F=k7_partfun1(A, D, E))  =>  (r2_hidden(F, k1_relset_1(A, C)) & E=k7_partfun1(B, C, F)) )  &  ( (r2_hidden(F, k1_relset_1(A, C)) & E=k7_partfun1(B, C, F))  =>  (r2_hidden(E, k2_relset_1(B, C)) & F=k7_partfun1(A, D, E)) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t4_partfun2, axiom,  (! [A] :  ( ~ (v1_xboole_0(A))  =>  (! [B] :  ( ~ (v1_xboole_0(B))  =>  (! [C] :  ( ~ (v1_xboole_0(C))  =>  (! [D] :  (m1_subset_1(D, A) =>  (! [E] :  ( (v1_funct_1(E) & m1_subset_1(E, k1_zfmisc_1(k2_zfmisc_1(A, B))))  =>  (! [F] :  ( (v1_funct_1(F) & m1_subset_1(F, k1_zfmisc_1(k2_zfmisc_1(B, C))))  =>  ( (r2_hidden(D, k1_relset_1(A, E)) & r2_hidden(k7_partfun1(B, E, D), k1_relset_1(B, F)))  => k7_partfun1(C, k1_partfun1(A, B, B, C, E, F), D)=k7_partfun1(C, F, k7_partfun1(B, E, D))) ) ) ) ) ) ) ) ) ) ) ) ) ).
