fof(t25_yellow19, conjecture,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  (m1_subset_1(B, k1_zfmisc_1(u1_struct_0(A))) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r2_hidden(C, k2_pre_topc(A, B)) <=>  (? [D] :  ( ( ~ (v1_xboole_0(D))  &  (v1_subset_1(D, u1_struct_0(k3_yellow_1(k2_struct_0(A)))) &  (v2_waybel_0(D, k3_yellow_1(k2_struct_0(A))) &  (v13_waybel_0(D, k3_yellow_1(k2_struct_0(A))) & m1_subset_1(D, k1_zfmisc_1(u1_struct_0(k3_yellow_1(k2_struct_0(A)))))) ) ) )  &  (r2_hidden(B, D) & r1_waybel_7(A, D, C)) ) ) ) ) ) ) ) ) ) ).
fof(d1_yellow_8, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_pre_topc(A))  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, k1_zfmisc_1(k1_zfmisc_1(u1_struct_0(A)))) =>  (v1_yellow_8(C, A, B) <=>  (r2_hidden(B, k8_setfam_1(u1_struct_0(A), C)) &  (! [D] :  (m1_subset_1(D, k1_zfmisc_1(u1_struct_0(A))) =>  ~ ( (v3_pre_topc(D, A) &  (r2_hidden(B, D) &  (! [E] :  (m1_subset_1(E, k1_zfmisc_1(u1_struct_0(A))) =>  ~ ( (r2_hidden(E, C) & r1_tarski(E, D)) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(d4_waybel_7, axiom,  (! [A] :  ( (v2_pre_topc(A) & l1_pre_topc(A))  =>  (! [B] :  (! [C] :  (r1_waybel_7(A, B, C) <=>  (! [D] :  (m1_subset_1(D, k1_zfmisc_1(u1_struct_0(A))) =>  ( (v3_pre_topc(D, A) & r2_hidden(C, D))  =>  (! [E] :  ~ ( (r2_hidden(E, B) & r1_xboole_0(D, E)) ) ) ) ) ) ) ) ) ) ) ).
fof(dt_k2_yellow19, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ~ (v2_struct_0(B))  & l1_waybel_0(B, A)) )  => m1_subset_1(k2_yellow19(A, B), k1_zfmisc_1(u1_struct_0(k3_yellow_1(k2_struct_0(A)))))) ) ).
fof(dt_l1_pre_topc, axiom,  (! [A] :  (l1_pre_topc(A) => l1_struct_0(A)) ) ).
fof(dt_o_2_4_topgen_2, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  & m1_subset_1(B, u1_struct_0(A)))  =>  (v1_tops_2(o_2_4_topgen_2(A, B), A) &  (v1_yellow_8(o_2_4_topgen_2(A, B), A, B) & m1_subset_1(o_2_4_topgen_2(A, B), k1_zfmisc_1(k1_zfmisc_1(u1_struct_0(A))))) ) ) ) ).
fof(fc2_yellow19, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ~ (v2_struct_0(B))  & l1_waybel_0(B, A)) )  =>  ( ~ (v1_xboole_0(k2_yellow19(A, B)))  & v13_waybel_0(k2_yellow19(A, B), k3_yellow_1(k2_struct_0(A)))) ) ) ).
fof(fc3_yellow19, axiom,  (! [A, B] :  ( ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  &  ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) ) )  =>  (v1_subset_1(k2_yellow19(A, B), u1_struct_0(k3_yellow_1(k2_struct_0(A)))) & v2_waybel_0(k2_yellow19(A, B), k3_yellow_1(k2_struct_0(A)))) ) ) ).
fof(symmetry_r1_xboole_0, axiom,  (! [A, B] :  (r1_xboole_0(A, B) => r1_xboole_0(B, A)) ) ).
fof(t10_yellow19, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_struct_0(A))  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & l1_waybel_0(B, A))  =>  (! [C] :  (r2_hidden(C, k2_yellow19(A, B)) <=>  (r1_waybel_0(A, B, C) & m1_subset_1(C, k1_zfmisc_1(u1_struct_0(A)))) ) ) ) ) ) ) ).
fof(t11_yellow19, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  &  (v4_orders_2(B) &  (v7_waybel_0(B) & l1_waybel_0(B, A)) ) )  =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r3_waybel_9(A, B, C) <=> r1_waybel_7(A, k2_yellow19(A, B), C)) ) ) ) ) ) ) ).
fof(t12_yellow_8, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  & l1_pre_topc(A))  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  ( (v1_tops_2(C, A) &  (v1_yellow_8(C, A, B) & m1_subset_1(C, k1_zfmisc_1(k1_zfmisc_1(u1_struct_0(A))))) )  =>  (! [D] :  (m1_subset_1(D, k1_zfmisc_1(u1_struct_0(A))) =>  (r2_hidden(D, C) =>  (v3_pre_topc(D, A) & r2_hidden(B, D)) ) ) ) ) ) ) ) ) ) ).
fof(t21_yellow19, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  (m1_subset_1(B, k1_zfmisc_1(u1_struct_0(A))) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r2_hidden(C, k2_pre_topc(A, B)) <=>  (? [D] :  ( ( ~ (v2_struct_0(D))  &  (v4_orders_2(D) &  (v7_waybel_0(D) & l1_waybel_0(D, A)) ) )  &  (r1_waybel_0(A, D, B) & r3_waybel_9(A, D, C)) ) ) ) ) ) ) ) ) ) ).
fof(t24_pre_topc, axiom,  (! [A] :  (l1_pre_topc(A) =>  (! [B] :  (m1_subset_1(B, k1_zfmisc_1(u1_struct_0(A))) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r2_hidden(C, k2_pre_topc(A, B)) <=>  ( ~ (v2_struct_0(A))  &  (! [D] :  (m1_subset_1(D, k1_zfmisc_1(u1_struct_0(A))) =>  ~ ( (v3_pre_topc(D, A) &  (r2_hidden(C, D) & r1_xboole_0(B, D)) ) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t63_xboole_1, axiom,  (! [A] :  (! [B] :  (! [C] :  ( (r1_tarski(A, B) & r1_xboole_0(B, C))  => r1_xboole_0(A, C)) ) ) ) ).
