fof(t37_yellow_0, conjecture,  (! [A] :  ( (v4_orders_2(A) &  (v5_orders_2(A) & l1_orders_2(A)) )  =>  (! [B] :  (! [C] :  ( (r2_yellow_0(A, B) &  (r2_yellow_0(A, C) & r2_yellow_0(A, k2_xboole_0(B, C))) )  => k2_yellow_0(A, k2_xboole_0(B, C))=k11_lattice3(A, k2_yellow_0(A, B), k2_yellow_0(A, C))) ) ) ) ) ).
fof(commutativity_k2_xboole_0, axiom,  (! [A, B] : k2_xboole_0(A, B)=k2_xboole_0(B, A)) ).
fof(dt_k2_yellow_0, axiom,  (! [A, B] :  (l1_orders_2(A) => m1_subset_1(k2_yellow_0(A, B), u1_struct_0(A))) ) ).
fof(t10_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (! [C] :  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( ( (r1_lattice3(A, B, D) & r1_lattice3(A, C, D))  => r1_lattice3(A, k2_xboole_0(B, C), D))  &  ( (r2_lattice3(A, B, D) & r2_lattice3(A, C, D))  => r2_lattice3(A, k2_xboole_0(B, C), D)) ) ) ) ) ) ) ) ).
fof(t19_yellow_0, axiom,  (! [A] :  ( (v5_orders_2(A) & l1_orders_2(A))  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  ( ( (D=k11_lattice3(A, B, C) & r2_yellow_0(A, k2_tarski(B, C)))  =>  (r1_orders_2(A, D, B) &  (r1_orders_2(A, D, C) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, E, B) & r1_orders_2(A, E, C))  => r1_orders_2(A, E, D)) ) ) ) ) )  &  ( (r1_orders_2(A, D, B) &  (r1_orders_2(A, D, C) &  (! [E] :  (m1_subset_1(E, u1_struct_0(A)) =>  ( (r1_orders_2(A, E, B) & r1_orders_2(A, E, C))  => r1_orders_2(A, E, D)) ) ) ) )  =>  (D=k11_lattice3(A, B, C) & r2_yellow_0(A, k2_tarski(B, C))) ) ) ) ) ) ) ) ) ) ) ).
fof(t31_yellow_0, axiom,  (! [A] :  ( (v5_orders_2(A) & l1_orders_2(A))  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  ( ( (B=k2_yellow_0(A, C) & r2_yellow_0(A, C))  =>  (r1_lattice3(A, C, B) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r1_lattice3(A, C, D) => r1_orders_2(A, D, B)) ) ) ) )  &  ( (r1_lattice3(A, C, B) &  (! [D] :  (m1_subset_1(D, u1_struct_0(A)) =>  (r1_lattice3(A, C, D) => r1_orders_2(A, D, B)) ) ) )  =>  (B=k2_yellow_0(A, C) & r2_yellow_0(A, C)) ) ) ) ) ) ) ) ).
fof(t35_yellow_0, axiom,  (! [A] :  (l1_orders_2(A) =>  (! [B] :  (! [C] :  ( (r1_tarski(B, C) &  (r2_yellow_0(A, B) & r2_yellow_0(A, C)) )  => r1_orders_2(A, k2_yellow_0(A, C), k2_yellow_0(A, B))) ) ) ) ) ).
fof(t4_yellow_0, axiom,  (! [A] :  ( (v4_orders_2(A) & l1_orders_2(A))  =>  (! [B] :  (m1_subset_1(B, u1_struct_0(A)) =>  (! [C] :  (m1_subset_1(C, u1_struct_0(A)) =>  (r1_orders_2(A, B, C) =>  (! [D] :  ( (r1_lattice3(A, D, C) => r1_lattice3(A, D, B))  &  (r2_lattice3(A, D, B) => r2_lattice3(A, D, C)) ) ) ) ) ) ) ) ) ) ).
fof(t7_xboole_1, axiom,  (! [A] :  (! [B] : r1_tarski(A, k2_xboole_0(A, B))) ) ).
