fof(t40_tmap_1, conjecture,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  &  (v1_borsuk_1(D, A) & m1_pre_topc(D, A)) )  =>  ( (m1_pre_topc(B, D) & r1_tsep_1(D, C))  =>  ( (v1_borsuk_1(B, k1_tsep_1(A, B, C)) & m1_pre_topc(B, k1_tsep_1(A, B, C)))  &  (v1_borsuk_1(B, k1_tsep_1(A, C, B)) & m1_pre_topc(B, k1_tsep_1(A, C, B))) ) ) ) ) ) ) ) ) ) ) ).
fof(cc1_pre_topc, axiom,  (! [A] :  ( (v2_pre_topc(A) & l1_pre_topc(A))  =>  (! [B] :  (m1_pre_topc(B, A) => v2_pre_topc(B)) ) ) ) ).
fof(commutativity_k1_tsep_1, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  & l1_pre_topc(A))  &  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  &  ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A)) ) )  => k1_tsep_1(A, B, C)=k1_tsep_1(A, C, B)) ) ).
fof(dt_k1_tsep_1, axiom,  (! [A, B, C] :  ( ( ( ~ (v2_struct_0(A))  & l1_pre_topc(A))  &  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  &  ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A)) ) )  =>  ( ~ (v2_struct_0(k1_tsep_1(A, B, C)))  &  (v1_pre_topc(k1_tsep_1(A, B, C)) & m1_pre_topc(k1_tsep_1(A, B, C), A)) ) ) ) ).
fof(dt_m1_pre_topc, axiom,  (! [A] :  (l1_pre_topc(A) =>  (! [B] :  (m1_pre_topc(B, A) => l1_pre_topc(B)) ) ) ) ).
fof(t17_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (m1_pre_topc(B, C) =>  ( ~ (r1_tsep_1(B, C))  &  ~ (r1_tsep_1(C, B)) ) ) ) ) ) ) ) ) ).
fof(t18_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  (m1_pre_topc(B, C) =>  ( (r1_tsep_1(B, D) & r1_tsep_1(D, B))  |  ( ~ (r1_tsep_1(C, D))  &  ~ (r1_tsep_1(D, C)) ) ) ) ) ) ) ) ) ) ) ) ).
fof(t22_tsep_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  => m1_pre_topc(B, k1_tsep_1(A, B, C))) ) ) ) ) ) ).
fof(t28_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  & m1_pre_topc(C, A))  =>  (! [D] :  ( ( ~ (v2_struct_0(D))  & m1_pre_topc(D, A))  =>  (m1_pre_topc(B, C) =>  ( ( ~ (r1_tsep_1(C, D))  &  ~ (r1_tsep_1(D, C)) )  |  (k2_tsep_1(A, C, k1_tsep_1(A, B, D))=g1_pre_topc(u1_struct_0(B), u1_pre_topc(B)) & k2_tsep_1(A, C, k1_tsep_1(A, D, B))=g1_pre_topc(u1_struct_0(B), u1_pre_topc(B))) ) ) ) ) ) ) ) ) ) ) ).
fof(t38_tmap_1, axiom,  (! [A] :  ( ( ~ (v2_struct_0(A))  &  (v2_pre_topc(A) & l1_pre_topc(A)) )  =>  (! [B] :  ( ( ~ (v2_struct_0(B))  & m1_pre_topc(B, A))  =>  (! [C] :  ( ( ~ (v2_struct_0(C))  &  (v1_borsuk_1(C, A) & m1_pre_topc(C, A)) )  =>  ( ~ (r1_tsep_1(C, B))  =>  (v1_borsuk_1(k2_tsep_1(A, C, B), B) & m1_pre_topc(k2_tsep_1(A, C, B), B)) ) ) ) ) ) ) ) ).
fof(t8_tmap_1, axiom,  (! [A] :  ( (v2_pre_topc(A) & l1_pre_topc(A))  =>  (! [B] :  ( (v2_pre_topc(B) & l1_pre_topc(B))  =>  (! [C] :  ( (v2_pre_topc(C) & l1_pre_topc(C))  =>  (C=g1_pre_topc(u1_struct_0(B), u1_pre_topc(B)) =>  ( (v1_borsuk_1(B, A) & m1_pre_topc(B, A))  <=>  (v1_borsuk_1(C, A) & m1_pre_topc(C, A)) ) ) ) ) ) ) ) ) ).
