fof(t77_mcart_1, conjecture,  (! [A] :  (! [B] :  ( ~ (v1_xboole_0(B))  =>  (! [C] :  ( ~ (v1_xboole_0(C))  =>  (! [D] :  ( ~ (v1_xboole_0(D))  =>  (! [E] :  ( ~ (v1_xboole_0(E))  =>  (! [F] :  (m1_subset_1(F, k4_zfmisc_1(B, C, D, E)) =>  ( (! [G] :  (m1_subset_1(G, B) =>  (! [H] :  (m1_subset_1(H, C) =>  (! [I] :  (m1_subset_1(I, D) =>  (! [J] :  (m1_subset_1(J, E) =>  (F=k6_xtuple_0(G, H, I, J) => A=I) ) ) ) ) ) ) ) )  => A=k6_mcart_1(B, C, D, E, F)) ) ) ) ) ) ) ) ) ) ) ) ).
fof(cc2_mcart_1, axiom,  (! [A, B, C, D] :  ( ( ~ (v1_xboole_0(A))  &  ( ~ (v1_xboole_0(B))  &  ( ~ (v1_xboole_0(C))  &  ~ (v1_xboole_0(D)) ) ) )  =>  (! [E] :  (m1_subset_1(E, k4_zfmisc_1(A, B, C, D)) => v3_xtuple_0(E)) ) ) ) ).
fof(dt_k4_mcart_1, axiom,  (! [A, B, C, D, E] :  ( ( ~ (v1_xboole_0(A))  &  ( ~ (v1_xboole_0(B))  &  ( ~ (v1_xboole_0(C))  &  ( ~ (v1_xboole_0(D))  & m1_subset_1(E, k4_zfmisc_1(A, B, C, D))) ) ) )  => m1_subset_1(k4_mcart_1(A, B, C, D, E), A)) ) ).
fof(dt_k5_mcart_1, axiom,  (! [A, B, C, D, E] :  ( ( ~ (v1_xboole_0(A))  &  ( ~ (v1_xboole_0(B))  &  ( ~ (v1_xboole_0(C))  &  ( ~ (v1_xboole_0(D))  & m1_subset_1(E, k4_zfmisc_1(A, B, C, D))) ) ) )  => m1_subset_1(k5_mcart_1(A, B, C, D, E), B)) ) ).
fof(dt_k6_mcart_1, axiom,  (! [A, B, C, D, E] :  ( ( ~ (v1_xboole_0(A))  &  ( ~ (v1_xboole_0(B))  &  ( ~ (v1_xboole_0(C))  &  ( ~ (v1_xboole_0(D))  & m1_subset_1(E, k4_zfmisc_1(A, B, C, D))) ) ) )  => m1_subset_1(k6_mcart_1(A, B, C, D, E), C)) ) ).
fof(dt_k7_mcart_1, axiom,  (! [A, B, C, D, E] :  ( ( ~ (v1_xboole_0(A))  &  ( ~ (v1_xboole_0(B))  &  ( ~ (v1_xboole_0(C))  &  ( ~ (v1_xboole_0(D))  & m1_subset_1(E, k4_zfmisc_1(A, B, C, D))) ) ) )  => m1_subset_1(k7_mcart_1(A, B, C, D, E), D)) ) ).
fof(rd12_xtuple_0, axiom,  (! [A] :  (v3_xtuple_0(A) => k6_xtuple_0(k7_xtuple_0(A), k8_xtuple_0(A), k5_xtuple_0(A), k2_xtuple_0(A))=A) ) ).
fof(redefinition_k4_mcart_1, axiom,  (! [A, B, C, D, E] :  ( ( ~ (v1_xboole_0(A))  &  ( ~ (v1_xboole_0(B))  &  ( ~ (v1_xboole_0(C))  &  ( ~ (v1_xboole_0(D))  & m1_subset_1(E, k4_zfmisc_1(A, B, C, D))) ) ) )  => k4_mcart_1(A, B, C, D, E)=k7_xtuple_0(E)) ) ).
fof(redefinition_k5_mcart_1, axiom,  (! [A, B, C, D, E] :  ( ( ~ (v1_xboole_0(A))  &  ( ~ (v1_xboole_0(B))  &  ( ~ (v1_xboole_0(C))  &  ( ~ (v1_xboole_0(D))  & m1_subset_1(E, k4_zfmisc_1(A, B, C, D))) ) ) )  => k5_mcart_1(A, B, C, D, E)=k8_xtuple_0(E)) ) ).
fof(redefinition_k6_mcart_1, axiom,  (! [A, B, C, D, E] :  ( ( ~ (v1_xboole_0(A))  &  ( ~ (v1_xboole_0(B))  &  ( ~ (v1_xboole_0(C))  &  ( ~ (v1_xboole_0(D))  & m1_subset_1(E, k4_zfmisc_1(A, B, C, D))) ) ) )  => k6_mcart_1(A, B, C, D, E)=k5_xtuple_0(E)) ) ).
fof(redefinition_k7_mcart_1, axiom,  (! [A, B, C, D, E] :  ( ( ~ (v1_xboole_0(A))  &  ( ~ (v1_xboole_0(B))  &  ( ~ (v1_xboole_0(C))  &  ( ~ (v1_xboole_0(D))  & m1_subset_1(E, k4_zfmisc_1(A, B, C, D))) ) ) )  => k7_mcart_1(A, B, C, D, E)=k2_xtuple_0(E)) ) ).
